package com.fieldnation.service.transaction;

/**
 * Created by Michael Carver on 2/27/2015.
 */
interface WebTransactionConstants {
    String PARAM_ID = "PARAM_ID";
    String PARAM_LISTENER_NAME = "PARAM_LISTENER_NAME";
    String PARAM_LISTENER_PARAMS = "PARAM_LISTENER_PARAMS";
    String PARAM_USE_AUTH = "PARAM_USE_AUTH";
    String PARAM_STATE = "PARAM_STATE";
    String PARAM_PRIORITY = "PARAM_PRIORITY";
    String PARAM_REQUEST = "PARAM_REQUEST";
    String PARAM_KEY = "PARAM_KEY";
    String PARAM_TRANSFORM_LIST = "PARAM_TRANSFORM_LIST";
    String PARAM_IS_SYNC = "PARAM_IS_SYNC";
    String PARAM_QUEUE_TIME = "PARAM_QUEUE_TIME";
    String PARAM_WIFI_REQUIRED = "PARAM_WIFI_REQUIRED";
    String PARAM_TRACK = "PARAM_TRACK";
    String PARAM_TIMING_KEY = "timingKey";

    String PARAM_NOTIFICATION_ID = "PARAM_NOTIFICATION_ID";
    String PARAM_NOTIFICATION_START = "PARAM_NOTIFICATION_START";
    String PARAM_NOTIFICATION_SUCCESS = "PARAM_NOTIFICATION_SUCCESS";
    String PARAM_NOTIFICATION_FAILED = "PARAM_NOTIFICATION_FAILED";
    String PARAM_NOTIFICATION_RETRY = "PARAM_NOTIFICATION_RETRY";
}
