/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ErrorTraceArgs;
import java.util.ArrayList;
import java.util.List;

/**
 * ErrorTrace
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class ErrorTrace {
  @Json(name="file")
  private String file = null;

  @Json(name="line")
  private Integer line = null;

  @Json(name="function")
  private String function = null;

  @Json(name="class")
  private String propertyClass = null;

  @Json(name="object")
  private Object object = null;

  @Json(name="type")
  private String type = null;

  @Json(name="args")
  private List<ErrorTraceArgs> args = new ArrayList<ErrorTraceArgs>();

  public ErrorTrace file(String file) {
    this.file = file;
    return this;
  }

   /**
   * Get file
   * @return file
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFile() {
    return file;
  }

  public void setFile(String file) {
    this.file = file;
  }

  public ErrorTrace line(Integer line) {
    this.line = line;
    return this;
  }

   /**
   * Get line
   * @return line
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLine() {
    return line;
  }

  public void setLine(Integer line) {
    this.line = line;
  }

  public ErrorTrace function(String function) {
    this.function = function;
    return this;
  }

   /**
   * Get function
   * @return function
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFunction() {
    return function;
  }

  public void setFunction(String function) {
    this.function = function;
  }

  public ErrorTrace propertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
    return this;
  }

   /**
   * Get propertyClass
   * @return propertyClass
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPropertyClass() {
    return propertyClass;
  }

  public void setPropertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
  }

  public ErrorTrace object(Object object) {
    this.object = object;
    return this;
  }

   /**
   * Get object
   * @return object
  **/
  @ApiModelProperty(example = "null", value = "")
  public Object getObject() {
    return object;
  }

  public void setObject(Object object) {
    this.object = object;
  }

  public ErrorTrace type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ErrorTrace args(List<ErrorTraceArgs> args) {
    this.args = args;
    return this;
  }

  public ErrorTrace addArgsItem(ErrorTraceArgs argsItem) {
    this.args.add(argsItem);
    return this;
  }

   /**
   * Get args
   * @return args
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ErrorTraceArgs> getArgs() {
    return args;
  }

  public void setArgs(List<ErrorTraceArgs> args) {
    this.args = args;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorTrace errorTrace = (ErrorTrace) o;
    return Objects.equals(this.file, errorTrace.file) &&
        Objects.equals(this.line, errorTrace.line) &&
        Objects.equals(this.function, errorTrace.function) &&
        Objects.equals(this.propertyClass, errorTrace.propertyClass) &&
        Objects.equals(this.object, errorTrace.object) &&
        Objects.equals(this.type, errorTrace.type) &&
        Objects.equals(this.args, errorTrace.args);
  }

  @Override
  public int hashCode() {
    return Objects.hash(file, line, function, propertyClass, object, type, args);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorTrace {\n");
    
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    line: ").append(toIndentedString(line)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

