/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.EventUpdateScheduleByWorkOrderOld;

/**
 * EventUpdateScheduleByWorkOrder
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class EventUpdateScheduleByWorkOrder {
  @Json(name="old")
  private EventUpdateScheduleByWorkOrderOld old = null;

  @Json(name="new")
  private EventUpdateScheduleByWorkOrderOld _new = null;

  public EventUpdateScheduleByWorkOrder old(EventUpdateScheduleByWorkOrderOld old) {
    this.old = old;
    return this;
  }

   /**
   * Get old
   * @return old
  **/
  @ApiModelProperty(example = "null", value = "")
  public EventUpdateScheduleByWorkOrderOld getOld() {
    return old;
  }

  public void setOld(EventUpdateScheduleByWorkOrderOld old) {
    this.old = old;
  }

  public EventUpdateScheduleByWorkOrder _new(EventUpdateScheduleByWorkOrderOld _new) {
    this._new = _new;
    return this;
  }

   /**
   * Get _new
   * @return _new
  **/
  @ApiModelProperty(example = "null", value = "")
  public EventUpdateScheduleByWorkOrderOld getNew() {
    return _new;
  }

  public void setNew(EventUpdateScheduleByWorkOrderOld _new) {
    this._new = _new;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventUpdateScheduleByWorkOrder eventUpdateScheduleByWorkOrder = (EventUpdateScheduleByWorkOrder) o;
    return Objects.equals(this.old, eventUpdateScheduleByWorkOrder.old) &&
        Objects.equals(this._new, eventUpdateScheduleByWorkOrder._new);
  }

  @Override
  public int hashCode() {
    return Objects.hash(old, _new);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventUpdateScheduleByWorkOrder {\n");
    
    sb.append("    old: ").append(toIndentedString(old)).append("\n");
    sb.append("    _new: ").append(toIndentedString(_new)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

