/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * Fee
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class Fee {
  @Json(name="id")
  private Integer id = null;

  @Json(name="amount")
  private BigDecimal amount = null;

  /**
   * Gets or Sets calculation
   */
  public enum CalculationEnum {
    @Json(name="percent")
    PERCENT("percent"),
    
    @Json(name="fixed")
    FIXED("fixed");

    private String value;

    CalculationEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @Json(name="calculation")
  private CalculationEnum calculation = null;

  @Json(name="modifier")
  private BigDecimal modifier = null;

  @Json(name="charged")
  private Boolean charged = null;

  public Fee id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Fee amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public Fee calculation(CalculationEnum calculation) {
    this.calculation = calculation;
    return this;
  }

   /**
   * Get calculation
   * @return calculation
  **/
  @ApiModelProperty(example = "null", value = "")
  public CalculationEnum getCalculation() {
    return calculation;
  }

  public void setCalculation(CalculationEnum calculation) {
    this.calculation = calculation;
  }

  public Fee modifier(BigDecimal modifier) {
    this.modifier = modifier;
    return this;
  }

   /**
   * Get modifier
   * @return modifier
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getModifier() {
    return modifier;
  }

  public void setModifier(BigDecimal modifier) {
    this.modifier = modifier;
  }

  public Fee charged(Boolean charged) {
    this.charged = charged;
    return this;
  }

   /**
   * Get charged
   * @return charged
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCharged() {
    return charged;
  }

  public void setCharged(Boolean charged) {
    this.charged = charged;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fee fee = (Fee) o;
    return Objects.equals(this.id, fee.id) &&
        Objects.equals(this.amount, fee.amount) &&
        Objects.equals(this.calculation, fee.calculation) &&
        Objects.equals(this.modifier, fee.modifier) &&
        Objects.equals(this.charged, fee.charged);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, amount, calculation, modifier, charged);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fee {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    calculation: ").append(toIndentedString(calculation)).append("\n");
    sb.append("    modifier: ").append(toIndentedString(modifier)).append("\n");
    sb.append("    charged: ").append(toIndentedString(charged)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

