/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * Manager
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class Manager {
  @Json(name="id")
  private Integer id = null;

  @Json(name="first_name")
  private String firstName = null;

  @Json(name="last_name")
  private String lastName = null;

  @Json(name="email")
  private String email = null;

  @Json(name="phone")
  private String phone = null;

  @Json(name="rating")
  private BigDecimal rating = null;

  @Json(name="ratings")
  private BigDecimal ratings = null;

  @Json(name="approval_days")
  private Integer approvalDays = null;

  @Json(name="review_period_days")
  private Integer reviewPeriodDays = null;

  public Manager id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Manager firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public Manager lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public Manager email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Manager phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public Manager rating(BigDecimal rating) {
    this.rating = rating;
    return this;
  }

   /**
   * Get rating
   * @return rating
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getRating() {
    return rating;
  }

  public void setRating(BigDecimal rating) {
    this.rating = rating;
  }

  public Manager ratings(BigDecimal ratings) {
    this.ratings = ratings;
    return this;
  }

   /**
   * Get ratings
   * @return ratings
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getRatings() {
    return ratings;
  }

  public void setRatings(BigDecimal ratings) {
    this.ratings = ratings;
  }

  public Manager approvalDays(Integer approvalDays) {
    this.approvalDays = approvalDays;
    return this;
  }

   /**
   * Get approvalDays
   * @return approvalDays
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getApprovalDays() {
    return approvalDays;
  }

  public void setApprovalDays(Integer approvalDays) {
    this.approvalDays = approvalDays;
  }

  public Manager reviewPeriodDays(Integer reviewPeriodDays) {
    this.reviewPeriodDays = reviewPeriodDays;
    return this;
  }

   /**
   * Get reviewPeriodDays
   * @return reviewPeriodDays
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getReviewPeriodDays() {
    return reviewPeriodDays;
  }

  public void setReviewPeriodDays(Integer reviewPeriodDays) {
    this.reviewPeriodDays = reviewPeriodDays;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Manager manager = (Manager) o;
    return Objects.equals(this.id, manager.id) &&
        Objects.equals(this.firstName, manager.firstName) &&
        Objects.equals(this.lastName, manager.lastName) &&
        Objects.equals(this.email, manager.email) &&
        Objects.equals(this.phone, manager.phone) &&
        Objects.equals(this.rating, manager.rating) &&
        Objects.equals(this.ratings, manager.ratings) &&
        Objects.equals(this.approvalDays, manager.approvalDays) &&
        Objects.equals(this.reviewPeriodDays, manager.reviewPeriodDays);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, firstName, lastName, email, phone, rating, ratings, approvalDays, reviewPeriodDays);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Manager {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    ratings: ").append(toIndentedString(ratings)).append("\n");
    sb.append("    approvalDays: ").append(toIndentedString(approvalDays)).append("\n");
    sb.append("    reviewPeriodDays: ").append(toIndentedString(reviewPeriodDays)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

