/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ListEnvelope;
import io.swagger.client.model.Message;
import java.util.ArrayList;
import java.util.List;

/**
 * Messages
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class Messages {
  @Json(name="metadata")
  private ListEnvelope metadata = null;

  /**
   * Gets or Sets actions
   */
  public enum ActionsEnum {
    @Json(name="add")
    ADD("add");

    private String value;

    ActionsEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @Json(name="actions")
  private List<ActionsEnum> actions = new ArrayList<ActionsEnum>();

  @Json(name="results")
  private Message results = null;

  @Json(name="sum")
  private Integer sum = null;

  @Json(name="problem_reported")
  private Boolean problemReported = null;

  public Messages metadata(ListEnvelope metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(example = "null", value = "")
  public ListEnvelope getMetadata() {
    return metadata;
  }

  public void setMetadata(ListEnvelope metadata) {
    this.metadata = metadata;
  }

  public Messages actions(List<ActionsEnum> actions) {
    this.actions = actions;
    return this;
  }

  public Messages addActionsItem(ActionsEnum actionsItem) {
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ActionsEnum> getActions() {
    return actions;
  }

  public void setActions(List<ActionsEnum> actions) {
    this.actions = actions;
  }

  public Messages results(Message results) {
    this.results = results;
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(example = "null", value = "")
  public Message getResults() {
    return results;
  }

  public void setResults(Message results) {
    this.results = results;
  }

  public Messages sum(Integer sum) {
    this.sum = sum;
    return this;
  }

   /**
   * Get sum
   * @return sum
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSum() {
    return sum;
  }

  public void setSum(Integer sum) {
    this.sum = sum;
  }

  public Messages problemReported(Boolean problemReported) {
    this.problemReported = problemReported;
    return this;
  }

   /**
   * Get problemReported
   * @return problemReported
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getProblemReported() {
    return problemReported;
  }

  public void setProblemReported(Boolean problemReported) {
    this.problemReported = problemReported;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Messages messages = (Messages) o;
    return Objects.equals(this.metadata, messages.metadata) &&
        Objects.equals(this.actions, messages.actions) &&
        Objects.equals(this.results, messages.results) &&
        Objects.equals(this.sum, messages.sum) &&
        Objects.equals(this.problemReported, messages.problemReported);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, actions, results, sum, problemReported);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Messages {\n");
    
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("    problemReported: ").append(toIndentedString(problemReported)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

