/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * MessageFrom
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class MessageFrom {
  @Json(name="id")
  private Integer id = null;

  @Json(name="name")
  private String name = null;

  @Json(name="thumbnail")
  private String thumbnail = null;

  @Json(name="hideWoManager")
  private Boolean hideWoManager = null;

  @Json(name="msgLink")
  private String msgLink = null;

  @Json(name="role")
  private String role = null;

  public MessageFrom id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public MessageFrom name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MessageFrom thumbnail(String thumbnail) {
    this.thumbnail = thumbnail;
    return this;
  }

   /**
   * Get thumbnail
   * @return thumbnail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getThumbnail() {
    return thumbnail;
  }

  public void setThumbnail(String thumbnail) {
    this.thumbnail = thumbnail;
  }

  public MessageFrom hideWoManager(Boolean hideWoManager) {
    this.hideWoManager = hideWoManager;
    return this;
  }

   /**
   * Get hideWoManager
   * @return hideWoManager
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getHideWoManager() {
    return hideWoManager;
  }

  public void setHideWoManager(Boolean hideWoManager) {
    this.hideWoManager = hideWoManager;
  }

  public MessageFrom msgLink(String msgLink) {
    this.msgLink = msgLink;
    return this;
  }

   /**
   * Get msgLink
   * @return msgLink
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMsgLink() {
    return msgLink;
  }

  public void setMsgLink(String msgLink) {
    this.msgLink = msgLink;
  }

  public MessageFrom role(String role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageFrom messageFrom = (MessageFrom) o;
    return Objects.equals(this.id, messageFrom.id) &&
        Objects.equals(this.name, messageFrom.name) &&
        Objects.equals(this.thumbnail, messageFrom.thumbnail) &&
        Objects.equals(this.hideWoManager, messageFrom.hideWoManager) &&
        Objects.equals(this.msgLink, messageFrom.msgLink) &&
        Objects.equals(this.role, messageFrom.role);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, thumbnail, hideWoManager, msgLink, role);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageFrom {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    hideWoManager: ").append(toIndentedString(hideWoManager)).append("\n");
    sb.append("    msgLink: ").append(toIndentedString(msgLink)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

