/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MilestonesCreated;
import java.math.BigDecimal;

/**
 * Milestones
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class Milestones {
  @Json(name="time_to_dispatch")
  private BigDecimal timeToDispatch = null;

  @Json(name="time_to_work_done")
  private BigDecimal timeToWorkDone = null;

  @Json(name="time_alive")
  private BigDecimal timeAlive = null;

  @Json(name="created")
  private MilestonesCreated created = null;

  @Json(name="published")
  private MilestonesCreated published = null;

  @Json(name="routed")
  private MilestonesCreated routed = null;

  @Json(name="assigned")
  private MilestonesCreated assigned = null;

  @Json(name="workdone")
  private MilestonesCreated workdone = null;

  @Json(name="approved")
  private MilestonesCreated approved = null;

  @Json(name="paid")
  private MilestonesCreated paid = null;

  @Json(name="canceled")
  private MilestonesCreated canceled = null;

  public Milestones timeToDispatch(BigDecimal timeToDispatch) {
    this.timeToDispatch = timeToDispatch;
    return this;
  }

   /**
   * Get timeToDispatch
   * @return timeToDispatch
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getTimeToDispatch() {
    return timeToDispatch;
  }

  public void setTimeToDispatch(BigDecimal timeToDispatch) {
    this.timeToDispatch = timeToDispatch;
  }

  public Milestones timeToWorkDone(BigDecimal timeToWorkDone) {
    this.timeToWorkDone = timeToWorkDone;
    return this;
  }

   /**
   * Get timeToWorkDone
   * @return timeToWorkDone
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getTimeToWorkDone() {
    return timeToWorkDone;
  }

  public void setTimeToWorkDone(BigDecimal timeToWorkDone) {
    this.timeToWorkDone = timeToWorkDone;
  }

  public Milestones timeAlive(BigDecimal timeAlive) {
    this.timeAlive = timeAlive;
    return this;
  }

   /**
   * Get timeAlive
   * @return timeAlive
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getTimeAlive() {
    return timeAlive;
  }

  public void setTimeAlive(BigDecimal timeAlive) {
    this.timeAlive = timeAlive;
  }

  public Milestones created(MilestonesCreated created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", value = "")
  public MilestonesCreated getCreated() {
    return created;
  }

  public void setCreated(MilestonesCreated created) {
    this.created = created;
  }

  public Milestones published(MilestonesCreated published) {
    this.published = published;
    return this;
  }

   /**
   * Get published
   * @return published
  **/
  @ApiModelProperty(example = "null", value = "")
  public MilestonesCreated getPublished() {
    return published;
  }

  public void setPublished(MilestonesCreated published) {
    this.published = published;
  }

  public Milestones routed(MilestonesCreated routed) {
    this.routed = routed;
    return this;
  }

   /**
   * Get routed
   * @return routed
  **/
  @ApiModelProperty(example = "null", value = "")
  public MilestonesCreated getRouted() {
    return routed;
  }

  public void setRouted(MilestonesCreated routed) {
    this.routed = routed;
  }

  public Milestones assigned(MilestonesCreated assigned) {
    this.assigned = assigned;
    return this;
  }

   /**
   * Get assigned
   * @return assigned
  **/
  @ApiModelProperty(example = "null", value = "")
  public MilestonesCreated getAssigned() {
    return assigned;
  }

  public void setAssigned(MilestonesCreated assigned) {
    this.assigned = assigned;
  }

  public Milestones workdone(MilestonesCreated workdone) {
    this.workdone = workdone;
    return this;
  }

   /**
   * Get workdone
   * @return workdone
  **/
  @ApiModelProperty(example = "null", value = "")
  public MilestonesCreated getWorkdone() {
    return workdone;
  }

  public void setWorkdone(MilestonesCreated workdone) {
    this.workdone = workdone;
  }

  public Milestones approved(MilestonesCreated approved) {
    this.approved = approved;
    return this;
  }

   /**
   * Get approved
   * @return approved
  **/
  @ApiModelProperty(example = "null", value = "")
  public MilestonesCreated getApproved() {
    return approved;
  }

  public void setApproved(MilestonesCreated approved) {
    this.approved = approved;
  }

  public Milestones paid(MilestonesCreated paid) {
    this.paid = paid;
    return this;
  }

   /**
   * Get paid
   * @return paid
  **/
  @ApiModelProperty(example = "null", value = "")
  public MilestonesCreated getPaid() {
    return paid;
  }

  public void setPaid(MilestonesCreated paid) {
    this.paid = paid;
  }

  public Milestones canceled(MilestonesCreated canceled) {
    this.canceled = canceled;
    return this;
  }

   /**
   * Get canceled
   * @return canceled
  **/
  @ApiModelProperty(example = "null", value = "")
  public MilestonesCreated getCanceled() {
    return canceled;
  }

  public void setCanceled(MilestonesCreated canceled) {
    this.canceled = canceled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Milestones milestones = (Milestones) o;
    return Objects.equals(this.timeToDispatch, milestones.timeToDispatch) &&
        Objects.equals(this.timeToWorkDone, milestones.timeToWorkDone) &&
        Objects.equals(this.timeAlive, milestones.timeAlive) &&
        Objects.equals(this.created, milestones.created) &&
        Objects.equals(this.published, milestones.published) &&
        Objects.equals(this.routed, milestones.routed) &&
        Objects.equals(this.assigned, milestones.assigned) &&
        Objects.equals(this.workdone, milestones.workdone) &&
        Objects.equals(this.approved, milestones.approved) &&
        Objects.equals(this.paid, milestones.paid) &&
        Objects.equals(this.canceled, milestones.canceled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeToDispatch, timeToWorkDone, timeAlive, created, published, routed, assigned, workdone, approved, paid, canceled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Milestones {\n");
    
    sb.append("    timeToDispatch: ").append(toIndentedString(timeToDispatch)).append("\n");
    sb.append("    timeToWorkDone: ").append(toIndentedString(timeToWorkDone)).append("\n");
    sb.append("    timeAlive: ").append(toIndentedString(timeAlive)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    published: ").append(toIndentedString(published)).append("\n");
    sb.append("    routed: ").append(toIndentedString(routed)).append("\n");
    sb.append("    assigned: ").append(toIndentedString(assigned)).append("\n");
    sb.append("    workdone: ").append(toIndentedString(workdone)).append("\n");
    sb.append("    approved: ").append(toIndentedString(approved)).append("\n");
    sb.append("    paid: ").append(toIndentedString(paid)).append("\n");
    sb.append("    canceled: ").append(toIndentedString(canceled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

