/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MilestonesCreatedLocal;

/**
 * MilestonesCreated
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class MilestonesCreated {
  @Json(name="utc")
  private String utc = null;

  @Json(name="local")
  private MilestonesCreatedLocal local = null;

  public MilestonesCreated utc(String utc) {
    this.utc = utc;
    return this;
  }

   /**
   * Get utc
   * @return utc
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUtc() {
    return utc;
  }

  public void setUtc(String utc) {
    this.utc = utc;
  }

  public MilestonesCreated local(MilestonesCreatedLocal local) {
    this.local = local;
    return this;
  }

   /**
   * Get local
   * @return local
  **/
  @ApiModelProperty(example = "null", value = "")
  public MilestonesCreatedLocal getLocal() {
    return local;
  }

  public void setLocal(MilestonesCreatedLocal local) {
    this.local = local;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MilestonesCreated milestonesCreated = (MilestonesCreated) o;
    return Objects.equals(this.utc, milestonesCreated.utc) &&
        Objects.equals(this.local, milestonesCreated.local);
  }

  @Override
  public int hashCode() {
    return Objects.hash(utc, local);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MilestonesCreated {\n");
    
    sb.append("    utc: ").append(toIndentedString(utc)).append("\n");
    sb.append("    local: ").append(toIndentedString(local)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

