/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Fee;
import io.swagger.client.model.PayBase;
import io.swagger.client.model.PayFees;
import io.swagger.client.model.PayFinance;
import io.swagger.client.model.PayRange;
import io.swagger.client.model.PricingInsights;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Pay
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class Pay {
  @Json(name="work_order_id")
  private Integer workOrderId = null;

  @Json(name="type")
  private String type = null;

  @Json(name="correlation_id")
  private String correlationId = null;

  @Json(name="role")
  private String role = null;

  @Json(name="actions")
  private List<String> actions = new ArrayList<String>();

  @Json(name="base")
  private PayBase base = null;

  @Json(name="additional")
  private PayBase additional = null;

  @Json(name="finance")
  private PayFinance finance = null;

  @Json(name="range")
  private PayRange range = null;

  @Json(name="status_id")
  private Integer statusId = null;

  @Json(name="pricing_insights")
  private PricingInsights pricingInsights = null;

  @Json(name="reported_hours")
  private BigDecimal reportedHours = null;

  @Json(name="number_of_devices")
  private BigDecimal numberOfDevices = null;

  @Json(name="labor_sum")
  private BigDecimal laborSum = null;

  @Json(name="total")
  private BigDecimal total = null;

  @Json(name="estimated_payment_date")
  private Date estimatedPaymentDate = null;

  @Json(name="hold")
  private Fee hold = null;

  @Json(name="payment")
  private Fee payment = null;

  @Json(name="fees")
  private PayFees fees = null;

  public Pay workOrderId(Integer workOrderId) {
    this.workOrderId = workOrderId;
    return this;
  }

   /**
   * Get workOrderId
   * @return workOrderId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWorkOrderId() {
    return workOrderId;
  }

  public void setWorkOrderId(Integer workOrderId) {
    this.workOrderId = workOrderId;
  }

  public Pay type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Pay correlationId(String correlationId) {
    this.correlationId = correlationId;
    return this;
  }

   /**
   * Get correlationId
   * @return correlationId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCorrelationId() {
    return correlationId;
  }

  public void setCorrelationId(String correlationId) {
    this.correlationId = correlationId;
  }

  public Pay role(String role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public Pay actions(List<String> actions) {
    this.actions = actions;
    return this;
  }

  public Pay addActionsItem(String actionsItem) {
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getActions() {
    return actions;
  }

  public void setActions(List<String> actions) {
    this.actions = actions;
  }

  public Pay base(PayBase base) {
    this.base = base;
    return this;
  }

   /**
   * Get base
   * @return base
  **/
  @ApiModelProperty(example = "null", value = "")
  public PayBase getBase() {
    return base;
  }

  public void setBase(PayBase base) {
    this.base = base;
  }

  public Pay additional(PayBase additional) {
    this.additional = additional;
    return this;
  }

   /**
   * Get additional
   * @return additional
  **/
  @ApiModelProperty(example = "null", value = "")
  public PayBase getAdditional() {
    return additional;
  }

  public void setAdditional(PayBase additional) {
    this.additional = additional;
  }

  public Pay finance(PayFinance finance) {
    this.finance = finance;
    return this;
  }

   /**
   * Get finance
   * @return finance
  **/
  @ApiModelProperty(example = "null", value = "")
  public PayFinance getFinance() {
    return finance;
  }

  public void setFinance(PayFinance finance) {
    this.finance = finance;
  }

  public Pay range(PayRange range) {
    this.range = range;
    return this;
  }

   /**
   * Get range
   * @return range
  **/
  @ApiModelProperty(example = "null", value = "")
  public PayRange getRange() {
    return range;
  }

  public void setRange(PayRange range) {
    this.range = range;
  }

  public Pay statusId(Integer statusId) {
    this.statusId = statusId;
    return this;
  }

   /**
   * Get statusId
   * @return statusId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatusId() {
    return statusId;
  }

  public void setStatusId(Integer statusId) {
    this.statusId = statusId;
  }

  public Pay pricingInsights(PricingInsights pricingInsights) {
    this.pricingInsights = pricingInsights;
    return this;
  }

   /**
   * Get pricingInsights
   * @return pricingInsights
  **/
  @ApiModelProperty(example = "null", value = "")
  public PricingInsights getPricingInsights() {
    return pricingInsights;
  }

  public void setPricingInsights(PricingInsights pricingInsights) {
    this.pricingInsights = pricingInsights;
  }

  public Pay reportedHours(BigDecimal reportedHours) {
    this.reportedHours = reportedHours;
    return this;
  }

   /**
   * Get reportedHours
   * @return reportedHours
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getReportedHours() {
    return reportedHours;
  }

  public void setReportedHours(BigDecimal reportedHours) {
    this.reportedHours = reportedHours;
  }

  public Pay numberOfDevices(BigDecimal numberOfDevices) {
    this.numberOfDevices = numberOfDevices;
    return this;
  }

   /**
   * Get numberOfDevices
   * @return numberOfDevices
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getNumberOfDevices() {
    return numberOfDevices;
  }

  public void setNumberOfDevices(BigDecimal numberOfDevices) {
    this.numberOfDevices = numberOfDevices;
  }

  public Pay laborSum(BigDecimal laborSum) {
    this.laborSum = laborSum;
    return this;
  }

   /**
   * Get laborSum
   * @return laborSum
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getLaborSum() {
    return laborSum;
  }

  public void setLaborSum(BigDecimal laborSum) {
    this.laborSum = laborSum;
  }

  public Pay total(BigDecimal total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getTotal() {
    return total;
  }

  public void setTotal(BigDecimal total) {
    this.total = total;
  }

  public Pay estimatedPaymentDate(Date estimatedPaymentDate) {
    this.estimatedPaymentDate = estimatedPaymentDate;
    return this;
  }

   /**
   * Get estimatedPaymentDate
   * @return estimatedPaymentDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getEstimatedPaymentDate() {
    return estimatedPaymentDate;
  }

  public void setEstimatedPaymentDate(Date estimatedPaymentDate) {
    this.estimatedPaymentDate = estimatedPaymentDate;
  }

  public Pay hold(Fee hold) {
    this.hold = hold;
    return this;
  }

   /**
   * Get hold
   * @return hold
  **/
  @ApiModelProperty(example = "null", value = "")
  public Fee getHold() {
    return hold;
  }

  public void setHold(Fee hold) {
    this.hold = hold;
  }

  public Pay payment(Fee payment) {
    this.payment = payment;
    return this;
  }

   /**
   * Get payment
   * @return payment
  **/
  @ApiModelProperty(example = "null", value = "")
  public Fee getPayment() {
    return payment;
  }

  public void setPayment(Fee payment) {
    this.payment = payment;
  }

  public Pay fees(PayFees fees) {
    this.fees = fees;
    return this;
  }

   /**
   * Get fees
   * @return fees
  **/
  @ApiModelProperty(example = "null", value = "")
  public PayFees getFees() {
    return fees;
  }

  public void setFees(PayFees fees) {
    this.fees = fees;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pay pay = (Pay) o;
    return Objects.equals(this.workOrderId, pay.workOrderId) &&
        Objects.equals(this.type, pay.type) &&
        Objects.equals(this.correlationId, pay.correlationId) &&
        Objects.equals(this.role, pay.role) &&
        Objects.equals(this.actions, pay.actions) &&
        Objects.equals(this.base, pay.base) &&
        Objects.equals(this.additional, pay.additional) &&
        Objects.equals(this.finance, pay.finance) &&
        Objects.equals(this.range, pay.range) &&
        Objects.equals(this.statusId, pay.statusId) &&
        Objects.equals(this.pricingInsights, pay.pricingInsights) &&
        Objects.equals(this.reportedHours, pay.reportedHours) &&
        Objects.equals(this.numberOfDevices, pay.numberOfDevices) &&
        Objects.equals(this.laborSum, pay.laborSum) &&
        Objects.equals(this.total, pay.total) &&
        Objects.equals(this.estimatedPaymentDate, pay.estimatedPaymentDate) &&
        Objects.equals(this.hold, pay.hold) &&
        Objects.equals(this.payment, pay.payment) &&
        Objects.equals(this.fees, pay.fees);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workOrderId, type, correlationId, role, actions, base, additional, finance, range, statusId, pricingInsights, reportedHours, numberOfDevices, laborSum, total, estimatedPaymentDate, hold, payment, fees);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pay {\n");
    
    sb.append("    workOrderId: ").append(toIndentedString(workOrderId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    correlationId: ").append(toIndentedString(correlationId)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    additional: ").append(toIndentedString(additional)).append("\n");
    sb.append("    finance: ").append(toIndentedString(finance)).append("\n");
    sb.append("    range: ").append(toIndentedString(range)).append("\n");
    sb.append("    statusId: ").append(toIndentedString(statusId)).append("\n");
    sb.append("    pricingInsights: ").append(toIndentedString(pricingInsights)).append("\n");
    sb.append("    reportedHours: ").append(toIndentedString(reportedHours)).append("\n");
    sb.append("    numberOfDevices: ").append(toIndentedString(numberOfDevices)).append("\n");
    sb.append("    laborSum: ").append(toIndentedString(laborSum)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    estimatedPaymentDate: ").append(toIndentedString(estimatedPaymentDate)).append("\n");
    sb.append("    hold: ").append(toIndentedString(hold)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("    fees: ").append(toIndentedString(fees)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

