/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * PayModifiersSum
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class PayModifiersSum {
  @Json(name="all")
  private BigDecimal all = null;

  @Json(name="charged")
  private BigDecimal charged = null;

  @Json(name="uncharged")
  private BigDecimal uncharged = null;

  public PayModifiersSum all(BigDecimal all) {
    this.all = all;
    return this;
  }

   /**
   * Get all
   * @return all
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getAll() {
    return all;
  }

  public void setAll(BigDecimal all) {
    this.all = all;
  }

  public PayModifiersSum charged(BigDecimal charged) {
    this.charged = charged;
    return this;
  }

   /**
   * Get charged
   * @return charged
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getCharged() {
    return charged;
  }

  public void setCharged(BigDecimal charged) {
    this.charged = charged;
  }

  public PayModifiersSum uncharged(BigDecimal uncharged) {
    this.uncharged = uncharged;
    return this;
  }

   /**
   * Get uncharged
   * @return uncharged
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getUncharged() {
    return uncharged;
  }

  public void setUncharged(BigDecimal uncharged) {
    this.uncharged = uncharged;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayModifiersSum payModifiersSum = (PayModifiersSum) o;
    return Objects.equals(this.all, payModifiersSum.all) &&
        Objects.equals(this.charged, payModifiersSum.charged) &&
        Objects.equals(this.uncharged, payModifiersSum.uncharged);
  }

  @Override
  public int hashCode() {
    return Objects.hash(all, charged, uncharged);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayModifiersSum {\n");
    
    sb.append("    all: ").append(toIndentedString(all)).append("\n");
    sb.append("    charged: ").append(toIndentedString(charged)).append("\n");
    sb.append("    uncharged: ").append(toIndentedString(uncharged)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

