/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ListEnvelope;
import io.swagger.client.model.PayModifier;
import io.swagger.client.model.PayModifiersSum;
import java.util.ArrayList;
import java.util.List;

/**
 * PayModifiers
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class PayModifiers {
  @Json(name="metadata")
  private ListEnvelope metadata = null;

  @Json(name="sum")
  private PayModifiersSum sum = null;

  /**
   * Gets or Sets actions
   */
  public enum ActionsEnum {
    @Json(name="edit")
    EDIT("edit");

    private String value;

    ActionsEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @Json(name="actions")
  private List<ActionsEnum> actions = new ArrayList<ActionsEnum>();

  @Json(name="results")
  private List<PayModifier> results = new ArrayList<PayModifier>();

  public PayModifiers metadata(ListEnvelope metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(example = "null", value = "")
  public ListEnvelope getMetadata() {
    return metadata;
  }

  public void setMetadata(ListEnvelope metadata) {
    this.metadata = metadata;
  }

  public PayModifiers sum(PayModifiersSum sum) {
    this.sum = sum;
    return this;
  }

   /**
   * Get sum
   * @return sum
  **/
  @ApiModelProperty(example = "null", value = "")
  public PayModifiersSum getSum() {
    return sum;
  }

  public void setSum(PayModifiersSum sum) {
    this.sum = sum;
  }

  public PayModifiers actions(List<ActionsEnum> actions) {
    this.actions = actions;
    return this;
  }

  public PayModifiers addActionsItem(ActionsEnum actionsItem) {
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ActionsEnum> getActions() {
    return actions;
  }

  public void setActions(List<ActionsEnum> actions) {
    this.actions = actions;
  }

  public PayModifiers results(List<PayModifier> results) {
    this.results = results;
    return this;
  }

  public PayModifiers addResultsItem(PayModifier resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<PayModifier> getResults() {
    return results;
  }

  public void setResults(List<PayModifier> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayModifiers payModifiers = (PayModifiers) o;
    return Objects.equals(this.metadata, payModifiers.metadata) &&
        Objects.equals(this.sum, payModifiers.sum) &&
        Objects.equals(this.actions, payModifiers.actions) &&
        Objects.equals(this.results, payModifiers.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, sum, actions, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayModifiers {\n");
    
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

