/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PricingInsightsRegionAverageRate;
import io.swagger.client.model.PricingInsightsRegionProviders;
import java.math.BigDecimal;

/**
 * PricingInsightsRegion
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class PricingInsightsRegion {
  @Json(name="name")
  private String name = null;

  @Json(name="id")
  private Integer id = null;

  @Json(name="distance")
  private BigDecimal distance = null;

  @Json(name="providers")
  private PricingInsightsRegionProviders providers = null;

  @Json(name="average_rate")
  private PricingInsightsRegionAverageRate averageRate = null;

  public PricingInsightsRegion name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PricingInsightsRegion id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public PricingInsightsRegion distance(BigDecimal distance) {
    this.distance = distance;
    return this;
  }

   /**
   * Get distance
   * @return distance
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getDistance() {
    return distance;
  }

  public void setDistance(BigDecimal distance) {
    this.distance = distance;
  }

  public PricingInsightsRegion providers(PricingInsightsRegionProviders providers) {
    this.providers = providers;
    return this;
  }

   /**
   * Get providers
   * @return providers
  **/
  @ApiModelProperty(example = "null", value = "")
  public PricingInsightsRegionProviders getProviders() {
    return providers;
  }

  public void setProviders(PricingInsightsRegionProviders providers) {
    this.providers = providers;
  }

  public PricingInsightsRegion averageRate(PricingInsightsRegionAverageRate averageRate) {
    this.averageRate = averageRate;
    return this;
  }

   /**
   * Get averageRate
   * @return averageRate
  **/
  @ApiModelProperty(example = "null", value = "")
  public PricingInsightsRegionAverageRate getAverageRate() {
    return averageRate;
  }

  public void setAverageRate(PricingInsightsRegionAverageRate averageRate) {
    this.averageRate = averageRate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricingInsightsRegion pricingInsightsRegion = (PricingInsightsRegion) o;
    return Objects.equals(this.name, pricingInsightsRegion.name) &&
        Objects.equals(this.id, pricingInsightsRegion.id) &&
        Objects.equals(this.distance, pricingInsightsRegion.distance) &&
        Objects.equals(this.providers, pricingInsightsRegion.providers) &&
        Objects.equals(this.averageRate, pricingInsightsRegion.averageRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, id, distance, providers, averageRate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricingInsightsRegion {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    providers: ").append(toIndentedString(providers)).append("\n");
    sb.append("    averageRate: ").append(toIndentedString(averageRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

