/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ProblemsNext;
import java.util.ArrayList;
import java.util.List;

/**
 * Problems
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class Problems {
  @Json(name="problem_id")
  private Integer problemId = null;

  @Json(name="reason")
  private String reason = null;

  @Json(name="next")
  private List<ProblemsNext> next = new ArrayList<ProblemsNext>();

  public Problems problemId(Integer problemId) {
    this.problemId = problemId;
    return this;
  }

   /**
   * Get problemId
   * @return problemId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getProblemId() {
    return problemId;
  }

  public void setProblemId(Integer problemId) {
    this.problemId = problemId;
  }

  public Problems reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public Problems next(List<ProblemsNext> next) {
    this.next = next;
    return this;
  }

  public Problems addNextItem(ProblemsNext nextItem) {
    this.next.add(nextItem);
    return this;
  }

   /**
   * Get next
   * @return next
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ProblemsNext> getNext() {
    return next;
  }

  public void setNext(List<ProblemsNext> next) {
    this.next = next;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Problems problems = (Problems) o;
    return Objects.equals(this.problemId, problems.problemId) &&
        Objects.equals(this.reason, problems.reason) &&
        Objects.equals(this.next, problems.next);
  }

  @Override
  public int hashCode() {
    return Objects.hash(problemId, reason, next);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Problems {\n");
    
    sb.append("    problemId: ").append(toIndentedString(problemId)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

