/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Pay;
import io.swagger.client.model.Schedule;
import io.swagger.client.model.User;
import io.swagger.client.model.WorkOrder;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Request
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class Request {
  @Json(name="id")
  private Integer id = null;

  @Json(name="counter")
  private Boolean counter = null;

  @Json(name="counter_notes")
  private String counterNotes = null;

  @Json(name="active")
  private Boolean active = null;

  @Json(name="created")
  private Date created = null;

  @Json(name="expires")
  private Date expires = null;

  @Json(name="schedule")
  private Schedule schedule = null;

  @Json(name="hour_estimate")
  private BigDecimal hourEstimate = null;

  @Json(name="notes")
  private String notes = null;

  @Json(name="user")
  private User user = null;

  @Json(name="work_order")
  private WorkOrder workOrder = null;

  @Json(name="pay")
  private Pay pay = null;

  public Request id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Request counter(Boolean counter) {
    this.counter = counter;
    return this;
  }

   /**
   * Get counter
   * @return counter
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCounter() {
    return counter;
  }

  public void setCounter(Boolean counter) {
    this.counter = counter;
  }

  public Request counterNotes(String counterNotes) {
    this.counterNotes = counterNotes;
    return this;
  }

   /**
   * Get counterNotes
   * @return counterNotes
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCounterNotes() {
    return counterNotes;
  }

  public void setCounterNotes(String counterNotes) {
    this.counterNotes = counterNotes;
  }

  public Request active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Request created(Date created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getCreated() {
    return created;
  }

  public void setCreated(Date created) {
    this.created = created;
  }

  public Request expires(Date expires) {
    this.expires = expires;
    return this;
  }

   /**
   * Get expires
   * @return expires
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getExpires() {
    return expires;
  }

  public void setExpires(Date expires) {
    this.expires = expires;
  }

  public Request schedule(Schedule schedule) {
    this.schedule = schedule;
    return this;
  }

   /**
   * Get schedule
   * @return schedule
  **/
  @ApiModelProperty(example = "null", value = "")
  public Schedule getSchedule() {
    return schedule;
  }

  public void setSchedule(Schedule schedule) {
    this.schedule = schedule;
  }

  public Request hourEstimate(BigDecimal hourEstimate) {
    this.hourEstimate = hourEstimate;
    return this;
  }

   /**
   * Get hourEstimate
   * @return hourEstimate
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getHourEstimate() {
    return hourEstimate;
  }

  public void setHourEstimate(BigDecimal hourEstimate) {
    this.hourEstimate = hourEstimate;
  }

  public Request notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public Request user(User user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(example = "null", value = "")
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public Request workOrder(WorkOrder workOrder) {
    this.workOrder = workOrder;
    return this;
  }

   /**
   * Get workOrder
   * @return workOrder
  **/
  @ApiModelProperty(example = "null", value = "")
  public WorkOrder getWorkOrder() {
    return workOrder;
  }

  public void setWorkOrder(WorkOrder workOrder) {
    this.workOrder = workOrder;
  }

  public Request pay(Pay pay) {
    this.pay = pay;
    return this;
  }

   /**
   * Get pay
   * @return pay
  **/
  @ApiModelProperty(example = "null", value = "")
  public Pay getPay() {
    return pay;
  }

  public void setPay(Pay pay) {
    this.pay = pay;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Request request = (Request) o;
    return Objects.equals(this.id, request.id) &&
        Objects.equals(this.counter, request.counter) &&
        Objects.equals(this.counterNotes, request.counterNotes) &&
        Objects.equals(this.active, request.active) &&
        Objects.equals(this.created, request.created) &&
        Objects.equals(this.expires, request.expires) &&
        Objects.equals(this.schedule, request.schedule) &&
        Objects.equals(this.hourEstimate, request.hourEstimate) &&
        Objects.equals(this.notes, request.notes) &&
        Objects.equals(this.user, request.user) &&
        Objects.equals(this.workOrder, request.workOrder) &&
        Objects.equals(this.pay, request.pay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, counter, counterNotes, active, created, expires, schedule, hourEstimate, notes, user, workOrder, pay);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Request {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    counter: ").append(toIndentedString(counter)).append("\n");
    sb.append("    counterNotes: ").append(toIndentedString(counterNotes)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("    hourEstimate: ").append(toIndentedString(hourEstimate)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    workOrder: ").append(toIndentedString(workOrder)).append("\n");
    sb.append("    pay: ").append(toIndentedString(pay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

