/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ScheduleEtaStatus;
import io.swagger.client.model.User;
import java.math.BigDecimal;
import java.util.Date;

/**
 * ScheduleEta
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class ScheduleEta {
  @Json(name="user")
  private User user = null;

  @Json(name="mode")
  private Boolean mode = null;

  @Json(name="start")
  private Date start = null;

  @Json(name="end")
  private Date end = null;

  @Json(name="hour_estimate")
  private BigDecimal hourEstimate = null;

  @Json(name="status")
  private ScheduleEtaStatus status = null;

  public ScheduleEta user(User user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(example = "null", value = "")
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public ScheduleEta mode(Boolean mode) {
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getMode() {
    return mode;
  }

  public void setMode(Boolean mode) {
    this.mode = mode;
  }

  public ScheduleEta start(Date start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getStart() {
    return start;
  }

  public void setStart(Date start) {
    this.start = start;
  }

  public ScheduleEta end(Date end) {
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getEnd() {
    return end;
  }

  public void setEnd(Date end) {
    this.end = end;
  }

  public ScheduleEta hourEstimate(BigDecimal hourEstimate) {
    this.hourEstimate = hourEstimate;
    return this;
  }

   /**
   * Get hourEstimate
   * @return hourEstimate
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getHourEstimate() {
    return hourEstimate;
  }

  public void setHourEstimate(BigDecimal hourEstimate) {
    this.hourEstimate = hourEstimate;
  }

  public ScheduleEta status(ScheduleEtaStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public ScheduleEtaStatus getStatus() {
    return status;
  }

  public void setStatus(ScheduleEtaStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleEta scheduleEta = (ScheduleEta) o;
    return Objects.equals(this.user, scheduleEta.user) &&
        Objects.equals(this.mode, scheduleEta.mode) &&
        Objects.equals(this.start, scheduleEta.start) &&
        Objects.equals(this.end, scheduleEta.end) &&
        Objects.equals(this.hourEstimate, scheduleEta.hourEstimate) &&
        Objects.equals(this.status, scheduleEta.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user, mode, start, end, hourEstimate, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleEta {\n");
    
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    hourEstimate: ").append(toIndentedString(hourEstimate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

