/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OnMyWay;
import io.swagger.client.model.ScheduleEta;
import io.swagger.client.model.ScheduleServiceWindow;
import io.swagger.client.model.TimeZone;
import java.util.ArrayList;
import java.util.List;

/**
 * Schedule
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class Schedule {
  @Json(name="work_order_id")
  private Integer workOrderId = null;

  @Json(name="correlation_id")
  private String correlationId = null;

  @Json(name="service_window")
  private ScheduleServiceWindow serviceWindow = null;

  @Json(name="eta")
  private ScheduleEta eta = null;

  @Json(name="on_my_way")
  private OnMyWay onMyWay = null;

  @Json(name="time_zone")
  private TimeZone timeZone = null;

  @Json(name="role")
  private String role = null;

  @Json(name="status_id")
  private Integer statusId = null;

  /**
   * Gets or Sets actions
   */
  public enum ActionsEnum {
    @Json(name="edit")
    EDIT("edit");

    private String value;

    ActionsEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @Json(name="actions")
  private List<ActionsEnum> actions = new ArrayList<ActionsEnum>();

  @Json(name="no_refresh")
  private Boolean noRefresh = null;

  public Schedule workOrderId(Integer workOrderId) {
    this.workOrderId = workOrderId;
    return this;
  }

   /**
   * Get workOrderId
   * @return workOrderId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWorkOrderId() {
    return workOrderId;
  }

  public void setWorkOrderId(Integer workOrderId) {
    this.workOrderId = workOrderId;
  }

  public Schedule correlationId(String correlationId) {
    this.correlationId = correlationId;
    return this;
  }

   /**
   * Get correlationId
   * @return correlationId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCorrelationId() {
    return correlationId;
  }

  public void setCorrelationId(String correlationId) {
    this.correlationId = correlationId;
  }

  public Schedule serviceWindow(ScheduleServiceWindow serviceWindow) {
    this.serviceWindow = serviceWindow;
    return this;
  }

   /**
   * Get serviceWindow
   * @return serviceWindow
  **/
  @ApiModelProperty(example = "null", value = "")
  public ScheduleServiceWindow getServiceWindow() {
    return serviceWindow;
  }

  public void setServiceWindow(ScheduleServiceWindow serviceWindow) {
    this.serviceWindow = serviceWindow;
  }

  public Schedule eta(ScheduleEta eta) {
    this.eta = eta;
    return this;
  }

   /**
   * Get eta
   * @return eta
  **/
  @ApiModelProperty(example = "null", value = "")
  public ScheduleEta getEta() {
    return eta;
  }

  public void setEta(ScheduleEta eta) {
    this.eta = eta;
  }

  public Schedule onMyWay(OnMyWay onMyWay) {
    this.onMyWay = onMyWay;
    return this;
  }

   /**
   * Get onMyWay
   * @return onMyWay
  **/
  @ApiModelProperty(example = "null", value = "")
  public OnMyWay getOnMyWay() {
    return onMyWay;
  }

  public void setOnMyWay(OnMyWay onMyWay) {
    this.onMyWay = onMyWay;
  }

  public Schedule timeZone(TimeZone timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Get timeZone
   * @return timeZone
  **/
  @ApiModelProperty(example = "null", value = "")
  public TimeZone getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(TimeZone timeZone) {
    this.timeZone = timeZone;
  }

  public Schedule role(String role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public Schedule statusId(Integer statusId) {
    this.statusId = statusId;
    return this;
  }

   /**
   * Get statusId
   * @return statusId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatusId() {
    return statusId;
  }

  public void setStatusId(Integer statusId) {
    this.statusId = statusId;
  }

  public Schedule actions(List<ActionsEnum> actions) {
    this.actions = actions;
    return this;
  }

  public Schedule addActionsItem(ActionsEnum actionsItem) {
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ActionsEnum> getActions() {
    return actions;
  }

  public void setActions(List<ActionsEnum> actions) {
    this.actions = actions;
  }

  public Schedule noRefresh(Boolean noRefresh) {
    this.noRefresh = noRefresh;
    return this;
  }

   /**
   * Get noRefresh
   * @return noRefresh
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getNoRefresh() {
    return noRefresh;
  }

  public void setNoRefresh(Boolean noRefresh) {
    this.noRefresh = noRefresh;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Schedule schedule = (Schedule) o;
    return Objects.equals(this.workOrderId, schedule.workOrderId) &&
        Objects.equals(this.correlationId, schedule.correlationId) &&
        Objects.equals(this.serviceWindow, schedule.serviceWindow) &&
        Objects.equals(this.eta, schedule.eta) &&
        Objects.equals(this.onMyWay, schedule.onMyWay) &&
        Objects.equals(this.timeZone, schedule.timeZone) &&
        Objects.equals(this.role, schedule.role) &&
        Objects.equals(this.statusId, schedule.statusId) &&
        Objects.equals(this.actions, schedule.actions) &&
        Objects.equals(this.noRefresh, schedule.noRefresh);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workOrderId, correlationId, serviceWindow, eta, onMyWay, timeZone, role, statusId, actions, noRefresh);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Schedule {\n");
    
    sb.append("    workOrderId: ").append(toIndentedString(workOrderId)).append("\n");
    sb.append("    correlationId: ").append(toIndentedString(correlationId)).append("\n");
    sb.append("    serviceWindow: ").append(toIndentedString(serviceWindow)).append("\n");
    sb.append("    eta: ").append(toIndentedString(eta)).append("\n");
    sb.append("    onMyWay: ").append(toIndentedString(onMyWay)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    statusId: ").append(toIndentedString(statusId)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    noRefresh: ").append(toIndentedString(noRefresh)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

