/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ShipmentCarrier;
import io.swagger.client.model.ShipmentTask;
import io.swagger.client.model.User;
import java.util.Date;

/**
 * Shipment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class Shipment {
  @Json(name="id")
  private Integer id = null;

  @Json(name="user")
  private User user = null;

  @Json(name="name")
  private String name = null;

  /**
   * Gets or Sets direction
   */
  public enum DirectionEnum {
    @Json(name="to site")
    TO_SITE("to site"),
    
    @Json(name="from site")
    FROM_SITE("from site");

    private String value;

    DirectionEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @Json(name="direction")
  private DirectionEnum direction = null;

  @Json(name="carrier")
  private ShipmentCarrier carrier = null;

  @Json(name="created")
  private Date created = null;

  @Json(name="task")
  private ShipmentTask task = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @Json(name="Arrived")
    ARRIVED("Arrived"),
    
    @Json(name="En Route")
    EN_ROUTE("En Route"),
    
    @Json(name="Error")
    ERROR("Error"),
    
    @Json(name="Lost")
    LOST("Lost"),
    
    @Json(name="New")
    NEW("New");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @Json(name="status")
  private StatusEnum status = null;

  public Shipment id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Shipment user(User user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(example = "null", value = "")
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public Shipment name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Shipment direction(DirectionEnum direction) {
    this.direction = direction;
    return this;
  }

   /**
   * Get direction
   * @return direction
  **/
  @ApiModelProperty(example = "null", value = "")
  public DirectionEnum getDirection() {
    return direction;
  }

  public void setDirection(DirectionEnum direction) {
    this.direction = direction;
  }

  public Shipment carrier(ShipmentCarrier carrier) {
    this.carrier = carrier;
    return this;
  }

   /**
   * Get carrier
   * @return carrier
  **/
  @ApiModelProperty(example = "null", value = "")
  public ShipmentCarrier getCarrier() {
    return carrier;
  }

  public void setCarrier(ShipmentCarrier carrier) {
    this.carrier = carrier;
  }

  public Shipment created(Date created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getCreated() {
    return created;
  }

  public void setCreated(Date created) {
    this.created = created;
  }

  public Shipment task(ShipmentTask task) {
    this.task = task;
    return this;
  }

   /**
   * Get task
   * @return task
  **/
  @ApiModelProperty(example = "null", value = "")
  public ShipmentTask getTask() {
    return task;
  }

  public void setTask(ShipmentTask task) {
    this.task = task;
  }

  public Shipment status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Shipment shipment = (Shipment) o;
    return Objects.equals(this.id, shipment.id) &&
        Objects.equals(this.user, shipment.user) &&
        Objects.equals(this.name, shipment.name) &&
        Objects.equals(this.direction, shipment.direction) &&
        Objects.equals(this.carrier, shipment.carrier) &&
        Objects.equals(this.created, shipment.created) &&
        Objects.equals(this.task, shipment.task) &&
        Objects.equals(this.status, shipment.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, user, name, direction, carrier, created, task, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Shipment {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    task: ").append(toIndentedString(task)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

