/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * ShipmentCarrier
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class ShipmentCarrier {
  @Json(name="name")
  private String name = null;

  @Json(name="other")
  private String other = null;

  @Json(name="tracking")
  private String tracking = null;

  @Json(name="arrival")
  private Date arrival = null;

  @Json(name="arrived")
  private Date arrived = null;

  public ShipmentCarrier name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ShipmentCarrier other(String other) {
    this.other = other;
    return this;
  }

   /**
   * Get other
   * @return other
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOther() {
    return other;
  }

  public void setOther(String other) {
    this.other = other;
  }

  public ShipmentCarrier tracking(String tracking) {
    this.tracking = tracking;
    return this;
  }

   /**
   * Get tracking
   * @return tracking
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTracking() {
    return tracking;
  }

  public void setTracking(String tracking) {
    this.tracking = tracking;
  }

  public ShipmentCarrier arrival(Date arrival) {
    this.arrival = arrival;
    return this;
  }

   /**
   * Get arrival
   * @return arrival
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getArrival() {
    return arrival;
  }

  public void setArrival(Date arrival) {
    this.arrival = arrival;
  }

  public ShipmentCarrier arrived(Date arrived) {
    this.arrived = arrived;
    return this;
  }

   /**
   * Get arrived
   * @return arrived
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getArrived() {
    return arrived;
  }

  public void setArrived(Date arrived) {
    this.arrived = arrived;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipmentCarrier shipmentCarrier = (ShipmentCarrier) o;
    return Objects.equals(this.name, shipmentCarrier.name) &&
        Objects.equals(this.other, shipmentCarrier.other) &&
        Objects.equals(this.tracking, shipmentCarrier.tracking) &&
        Objects.equals(this.arrival, shipmentCarrier.arrival) &&
        Objects.equals(this.arrived, shipmentCarrier.arrived);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, other, tracking, arrival, arrived);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipmentCarrier {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    other: ").append(toIndentedString(other)).append("\n");
    sb.append("    tracking: ").append(toIndentedString(tracking)).append("\n");
    sb.append("    arrival: ").append(toIndentedString(arrival)).append("\n");
    sb.append("    arrived: ").append(toIndentedString(arrived)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

