/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Location;
import java.util.ArrayList;
import java.util.List;

/**
 * StoredLocations
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class StoredLocations {
  @Json(name="work_order_id")
  private Integer workOrderId = null;

  /**
   * Gets or Sets mode
   */
  public enum ModeEnum {
    @Json(name="custom")
    CUSTOM("custom"),
    
    @Json(name="location")
    LOCATION("location"),
    
    @Json(name="remote")
    REMOTE("remote");

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @Json(name="mode")
  private ModeEnum mode = null;

  @Json(name="role")
  private String role = null;

  /**
   * Gets or Sets actions
   */
  public enum ActionsEnum {
    @Json(name="edit")
    EDIT("edit");

    private String value;

    ActionsEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @Json(name="actions")
  private ActionsEnum actions = null;

  @Json(name="results")
  private List<Location> results = new ArrayList<Location>();

  public StoredLocations workOrderId(Integer workOrderId) {
    this.workOrderId = workOrderId;
    return this;
  }

   /**
   * Get workOrderId
   * @return workOrderId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWorkOrderId() {
    return workOrderId;
  }

  public void setWorkOrderId(Integer workOrderId) {
    this.workOrderId = workOrderId;
  }

  public StoredLocations mode(ModeEnum mode) {
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @ApiModelProperty(example = "null", value = "")
  public ModeEnum getMode() {
    return mode;
  }

  public void setMode(ModeEnum mode) {
    this.mode = mode;
  }

  public StoredLocations role(String role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public StoredLocations actions(ActionsEnum actions) {
    this.actions = actions;
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @ApiModelProperty(example = "null", value = "")
  public ActionsEnum getActions() {
    return actions;
  }

  public void setActions(ActionsEnum actions) {
    this.actions = actions;
  }

  public StoredLocations results(List<Location> results) {
    this.results = results;
    return this;
  }

  public StoredLocations addResultsItem(Location resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Location> getResults() {
    return results;
  }

  public void setResults(List<Location> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoredLocations storedLocations = (StoredLocations) o;
    return Objects.equals(this.workOrderId, storedLocations.workOrderId) &&
        Objects.equals(this.mode, storedLocations.mode) &&
        Objects.equals(this.role, storedLocations.role) &&
        Objects.equals(this.actions, storedLocations.actions) &&
        Objects.equals(this.results, storedLocations.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workOrderId, mode, role, actions, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoredLocations {\n");
    
    sb.append("    workOrderId: ").append(toIndentedString(workOrderId)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

