/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Attachment;
import io.swagger.client.model.CheckInOut;
import io.swagger.client.model.CustomField;
import io.swagger.client.model.OnMyWay;
import io.swagger.client.model.Shipment;
import io.swagger.client.model.Signature;
import io.swagger.client.model.TaskAlert;
import io.swagger.client.model.TaskGroup;
import io.swagger.client.model.TaskType;
import io.swagger.client.model.TimeZone;
import io.swagger.client.model.User;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Task
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class Task {
  @Json(name="id")
  private Integer id = null;

  @Json(name="alerts")
  private List<TaskAlert> alerts = new ArrayList<TaskAlert>();

  @Json(name="label")
  private String label = null;

  @Json(name="group")
  private TaskGroup group = null;

  @Json(name="time_zone")
  private TimeZone timeZone = null;

  @Json(name="actions")
  private List<String> actions = new ArrayList<String>();

  @Json(name="type")
  private TaskType type = null;

  @Json(name="created")
  private Date created = null;

  @Json(name="author")
  private User author = null;

  @Json(name="completed")
  private Boolean completed = null;

  @Json(name="check_in")
  private CheckInOut checkIn = null;

  @Json(name="check_out")
  private CheckInOut checkOut = null;

  @Json(name="closing_notes")
  private String closingNotes = null;

  @Json(name="confirmed")
  private Boolean confirmed = null;

  @Json(name="ready_to_go")
  private Boolean readyToGo = null;

  @Json(name="on_my_way")
  private OnMyWay onMyWay = null;

  @Json(name="attachments")
  private List<Attachment> attachments = new ArrayList<Attachment>();

  @Json(name="custom_field")
  private CustomField customField = null;

  @Json(name="value")
  private String value = null;

  @Json(name="phone")
  private String phone = null;

  @Json(name="email")
  private String email = null;

  @Json(name="signature")
  private Signature signature = null;

  @Json(name="shipment")
  private Shipment shipment = null;

  @Json(name="attachment")
  private Attachment attachment = null;

  public Task id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Task alerts(List<TaskAlert> alerts) {
    this.alerts = alerts;
    return this;
  }

  public Task addAlertsItem(TaskAlert alertsItem) {
    this.alerts.add(alertsItem);
    return this;
  }

   /**
   * Get alerts
   * @return alerts
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<TaskAlert> getAlerts() {
    return alerts;
  }

  public void setAlerts(List<TaskAlert> alerts) {
    this.alerts = alerts;
  }

  public Task label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public Task group(TaskGroup group) {
    this.group = group;
    return this;
  }

   /**
   * Get group
   * @return group
  **/
  @ApiModelProperty(example = "null", value = "")
  public TaskGroup getGroup() {
    return group;
  }

  public void setGroup(TaskGroup group) {
    this.group = group;
  }

  public Task timeZone(TimeZone timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Get timeZone
   * @return timeZone
  **/
  @ApiModelProperty(example = "null", value = "")
  public TimeZone getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(TimeZone timeZone) {
    this.timeZone = timeZone;
  }

  public Task actions(List<String> actions) {
    this.actions = actions;
    return this;
  }

  public Task addActionsItem(String actionsItem) {
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getActions() {
    return actions;
  }

  public void setActions(List<String> actions) {
    this.actions = actions;
  }

  public Task type(TaskType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public TaskType getType() {
    return type;
  }

  public void setType(TaskType type) {
    this.type = type;
  }

  public Task created(Date created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getCreated() {
    return created;
  }

  public void setCreated(Date created) {
    this.created = created;
  }

  public Task author(User author) {
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @ApiModelProperty(example = "null", value = "")
  public User getAuthor() {
    return author;
  }

  public void setAuthor(User author) {
    this.author = author;
  }

  public Task completed(Boolean completed) {
    this.completed = completed;
    return this;
  }

   /**
   * Get completed
   * @return completed
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCompleted() {
    return completed;
  }

  public void setCompleted(Boolean completed) {
    this.completed = completed;
  }

  public Task checkIn(CheckInOut checkIn) {
    this.checkIn = checkIn;
    return this;
  }

   /**
   * Get checkIn
   * @return checkIn
  **/
  @ApiModelProperty(example = "null", value = "")
  public CheckInOut getCheckIn() {
    return checkIn;
  }

  public void setCheckIn(CheckInOut checkIn) {
    this.checkIn = checkIn;
  }

  public Task checkOut(CheckInOut checkOut) {
    this.checkOut = checkOut;
    return this;
  }

   /**
   * Get checkOut
   * @return checkOut
  **/
  @ApiModelProperty(example = "null", value = "")
  public CheckInOut getCheckOut() {
    return checkOut;
  }

  public void setCheckOut(CheckInOut checkOut) {
    this.checkOut = checkOut;
  }

  public Task closingNotes(String closingNotes) {
    this.closingNotes = closingNotes;
    return this;
  }

   /**
   * Get closingNotes
   * @return closingNotes
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClosingNotes() {
    return closingNotes;
  }

  public void setClosingNotes(String closingNotes) {
    this.closingNotes = closingNotes;
  }

  public Task confirmed(Boolean confirmed) {
    this.confirmed = confirmed;
    return this;
  }

   /**
   * Get confirmed
   * @return confirmed
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getConfirmed() {
    return confirmed;
  }

  public void setConfirmed(Boolean confirmed) {
    this.confirmed = confirmed;
  }

  public Task readyToGo(Boolean readyToGo) {
    this.readyToGo = readyToGo;
    return this;
  }

   /**
   * Get readyToGo
   * @return readyToGo
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getReadyToGo() {
    return readyToGo;
  }

  public void setReadyToGo(Boolean readyToGo) {
    this.readyToGo = readyToGo;
  }

  public Task onMyWay(OnMyWay onMyWay) {
    this.onMyWay = onMyWay;
    return this;
  }

   /**
   * Get onMyWay
   * @return onMyWay
  **/
  @ApiModelProperty(example = "null", value = "")
  public OnMyWay getOnMyWay() {
    return onMyWay;
  }

  public void setOnMyWay(OnMyWay onMyWay) {
    this.onMyWay = onMyWay;
  }

  public Task attachments(List<Attachment> attachments) {
    this.attachments = attachments;
    return this;
  }

  public Task addAttachmentsItem(Attachment attachmentsItem) {
    this.attachments.add(attachmentsItem);
    return this;
  }

   /**
   * Get attachments
   * @return attachments
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Attachment> getAttachments() {
    return attachments;
  }

  public void setAttachments(List<Attachment> attachments) {
    this.attachments = attachments;
  }

  public Task customField(CustomField customField) {
    this.customField = customField;
    return this;
  }

   /**
   * Get customField
   * @return customField
  **/
  @ApiModelProperty(example = "null", value = "")
  public CustomField getCustomField() {
    return customField;
  }

  public void setCustomField(CustomField customField) {
    this.customField = customField;
  }

  public Task value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public Task phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public Task email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Task signature(Signature signature) {
    this.signature = signature;
    return this;
  }

   /**
   * Get signature
   * @return signature
  **/
  @ApiModelProperty(example = "null", value = "")
  public Signature getSignature() {
    return signature;
  }

  public void setSignature(Signature signature) {
    this.signature = signature;
  }

  public Task shipment(Shipment shipment) {
    this.shipment = shipment;
    return this;
  }

   /**
   * Get shipment
   * @return shipment
  **/
  @ApiModelProperty(example = "null", value = "")
  public Shipment getShipment() {
    return shipment;
  }

  public void setShipment(Shipment shipment) {
    this.shipment = shipment;
  }

  public Task attachment(Attachment attachment) {
    this.attachment = attachment;
    return this;
  }

   /**
   * Get attachment
   * @return attachment
  **/
  @ApiModelProperty(example = "null", value = "")
  public Attachment getAttachment() {
    return attachment;
  }

  public void setAttachment(Attachment attachment) {
    this.attachment = attachment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Task task = (Task) o;
    return Objects.equals(this.id, task.id) &&
        Objects.equals(this.alerts, task.alerts) &&
        Objects.equals(this.label, task.label) &&
        Objects.equals(this.group, task.group) &&
        Objects.equals(this.timeZone, task.timeZone) &&
        Objects.equals(this.actions, task.actions) &&
        Objects.equals(this.type, task.type) &&
        Objects.equals(this.created, task.created) &&
        Objects.equals(this.author, task.author) &&
        Objects.equals(this.completed, task.completed) &&
        Objects.equals(this.checkIn, task.checkIn) &&
        Objects.equals(this.checkOut, task.checkOut) &&
        Objects.equals(this.closingNotes, task.closingNotes) &&
        Objects.equals(this.confirmed, task.confirmed) &&
        Objects.equals(this.readyToGo, task.readyToGo) &&
        Objects.equals(this.onMyWay, task.onMyWay) &&
        Objects.equals(this.attachments, task.attachments) &&
        Objects.equals(this.customField, task.customField) &&
        Objects.equals(this.value, task.value) &&
        Objects.equals(this.phone, task.phone) &&
        Objects.equals(this.email, task.email) &&
        Objects.equals(this.signature, task.signature) &&
        Objects.equals(this.shipment, task.shipment) &&
        Objects.equals(this.attachment, task.attachment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, alerts, label, group, timeZone, actions, type, created, author, completed, checkIn, checkOut, closingNotes, confirmed, readyToGo, onMyWay, attachments, customField, value, phone, email, signature, shipment, attachment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Task {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    alerts: ").append(toIndentedString(alerts)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    completed: ").append(toIndentedString(completed)).append("\n");
    sb.append("    checkIn: ").append(toIndentedString(checkIn)).append("\n");
    sb.append("    checkOut: ").append(toIndentedString(checkOut)).append("\n");
    sb.append("    closingNotes: ").append(toIndentedString(closingNotes)).append("\n");
    sb.append("    confirmed: ").append(toIndentedString(confirmed)).append("\n");
    sb.append("    readyToGo: ").append(toIndentedString(readyToGo)).append("\n");
    sb.append("    onMyWay: ").append(toIndentedString(onMyWay)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    customField: ").append(toIndentedString(customField)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    shipment: ").append(toIndentedString(shipment)).append("\n");
    sb.append("    attachment: ").append(toIndentedString(attachment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

