/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ListEnvelope;
import io.swagger.client.model.OnMyWay;
import io.swagger.client.model.TimeLog;
import io.swagger.client.model.TimeLogsConfirmed;
import io.swagger.client.model.TimeZone;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * TimeLogs
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class TimeLogs {
  @Json(name="metadata")
  private ListEnvelope metadata = null;

  @Json(name="time_zone")
  private TimeZone timeZone = null;

  @Json(name="should_verify")
  private Boolean shouldVerify = null;

  @Json(name="hours")
  private BigDecimal hours = null;

  @Json(name="status")
  private String status = null;

  @Json(name="confirmed")
  private TimeLogsConfirmed confirmed = null;

  @Json(name="onmyway")
  private OnMyWay onmyway = null;

  /**
   * Gets or Sets actions
   */
  public enum ActionsEnum {
    @Json(name="create")
    CREATE("create");

    private String value;

    ActionsEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @Json(name="actions")
  private ActionsEnum actions = null;

  @Json(name="results")
  private List<TimeLog> results = new ArrayList<TimeLog>();

  public TimeLogs metadata(ListEnvelope metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(example = "null", value = "")
  public ListEnvelope getMetadata() {
    return metadata;
  }

  public void setMetadata(ListEnvelope metadata) {
    this.metadata = metadata;
  }

  public TimeLogs timeZone(TimeZone timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Get timeZone
   * @return timeZone
  **/
  @ApiModelProperty(example = "null", value = "")
  public TimeZone getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(TimeZone timeZone) {
    this.timeZone = timeZone;
  }

  public TimeLogs shouldVerify(Boolean shouldVerify) {
    this.shouldVerify = shouldVerify;
    return this;
  }

   /**
   * Get shouldVerify
   * @return shouldVerify
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getShouldVerify() {
    return shouldVerify;
  }

  public void setShouldVerify(Boolean shouldVerify) {
    this.shouldVerify = shouldVerify;
  }

  public TimeLogs hours(BigDecimal hours) {
    this.hours = hours;
    return this;
  }

   /**
   * Get hours
   * @return hours
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getHours() {
    return hours;
  }

  public void setHours(BigDecimal hours) {
    this.hours = hours;
  }

  public TimeLogs status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public TimeLogs confirmed(TimeLogsConfirmed confirmed) {
    this.confirmed = confirmed;
    return this;
  }

   /**
   * Get confirmed
   * @return confirmed
  **/
  @ApiModelProperty(example = "null", value = "")
  public TimeLogsConfirmed getConfirmed() {
    return confirmed;
  }

  public void setConfirmed(TimeLogsConfirmed confirmed) {
    this.confirmed = confirmed;
  }

  public TimeLogs onmyway(OnMyWay onmyway) {
    this.onmyway = onmyway;
    return this;
  }

   /**
   * Get onmyway
   * @return onmyway
  **/
  @ApiModelProperty(example = "null", value = "")
  public OnMyWay getOnmyway() {
    return onmyway;
  }

  public void setOnmyway(OnMyWay onmyway) {
    this.onmyway = onmyway;
  }

  public TimeLogs actions(ActionsEnum actions) {
    this.actions = actions;
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @ApiModelProperty(example = "null", value = "")
  public ActionsEnum getActions() {
    return actions;
  }

  public void setActions(ActionsEnum actions) {
    this.actions = actions;
  }

  public TimeLogs results(List<TimeLog> results) {
    this.results = results;
    return this;
  }

  public TimeLogs addResultsItem(TimeLog resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<TimeLog> getResults() {
    return results;
  }

  public void setResults(List<TimeLog> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeLogs timeLogs = (TimeLogs) o;
    return Objects.equals(this.metadata, timeLogs.metadata) &&
        Objects.equals(this.timeZone, timeLogs.timeZone) &&
        Objects.equals(this.shouldVerify, timeLogs.shouldVerify) &&
        Objects.equals(this.hours, timeLogs.hours) &&
        Objects.equals(this.status, timeLogs.status) &&
        Objects.equals(this.confirmed, timeLogs.confirmed) &&
        Objects.equals(this.onmyway, timeLogs.onmyway) &&
        Objects.equals(this.actions, timeLogs.actions) &&
        Objects.equals(this.results, timeLogs.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, timeZone, shouldVerify, hours, status, confirmed, onmyway, actions, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeLogs {\n");
    
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    shouldVerify: ").append(toIndentedString(shouldVerify)).append("\n");
    sb.append("    hours: ").append(toIndentedString(hours)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    confirmed: ").append(toIndentedString(confirmed)).append("\n");
    sb.append("    onmyway: ").append(toIndentedString(onmyway)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

