/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CheckInOut;
import io.swagger.client.model.OnMyWay;
import io.swagger.client.model.TimeZone;
import io.swagger.client.model.User;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * TimeLog
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class TimeLog {
  @Json(name="work_order_id")
  private Integer workOrderId = null;

  @Json(name="time_zone")
  private TimeZone timeZone = null;

  @Json(name="in")
  private CheckInOut in = null;

  @Json(name="out")
  private CheckInOut out = null;

  @Json(name="devices")
  private BigDecimal devices = null;

  @Json(name="hours")
  private BigDecimal hours = null;

  @Json(name="verified")
  private Boolean verified = null;

  @Json(name="was_late")
  private Boolean wasLate = null;

  @Json(name="logged_by")
  private User loggedBy = null;

  @Json(name="on_my_way")
  private OnMyWay onMyWay = null;

  /**
   * Gets or Sets actions
   */
  public enum ActionsEnum {
    @Json(name="edit")
    EDIT("edit");

    private String value;

    ActionsEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @Json(name="actions")
  private List<ActionsEnum> actions = new ArrayList<ActionsEnum>();

  public TimeLog workOrderId(Integer workOrderId) {
    this.workOrderId = workOrderId;
    return this;
  }

   /**
   * Get workOrderId
   * @return workOrderId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWorkOrderId() {
    return workOrderId;
  }

  public void setWorkOrderId(Integer workOrderId) {
    this.workOrderId = workOrderId;
  }

  public TimeLog timeZone(TimeZone timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Get timeZone
   * @return timeZone
  **/
  @ApiModelProperty(example = "null", value = "")
  public TimeZone getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(TimeZone timeZone) {
    this.timeZone = timeZone;
  }

  public TimeLog in(CheckInOut in) {
    this.in = in;
    return this;
  }

   /**
   * Get in
   * @return in
  **/
  @ApiModelProperty(example = "null", value = "")
  public CheckInOut getIn() {
    return in;
  }

  public void setIn(CheckInOut in) {
    this.in = in;
  }

  public TimeLog out(CheckInOut out) {
    this.out = out;
    return this;
  }

   /**
   * Get out
   * @return out
  **/
  @ApiModelProperty(example = "null", value = "")
  public CheckInOut getOut() {
    return out;
  }

  public void setOut(CheckInOut out) {
    this.out = out;
  }

  public TimeLog devices(BigDecimal devices) {
    this.devices = devices;
    return this;
  }

   /**
   * Get devices
   * @return devices
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getDevices() {
    return devices;
  }

  public void setDevices(BigDecimal devices) {
    this.devices = devices;
  }

  public TimeLog hours(BigDecimal hours) {
    this.hours = hours;
    return this;
  }

   /**
   * Get hours
   * @return hours
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getHours() {
    return hours;
  }

  public void setHours(BigDecimal hours) {
    this.hours = hours;
  }

  public TimeLog verified(Boolean verified) {
    this.verified = verified;
    return this;
  }

   /**
   * Get verified
   * @return verified
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getVerified() {
    return verified;
  }

  public void setVerified(Boolean verified) {
    this.verified = verified;
  }

  public TimeLog wasLate(Boolean wasLate) {
    this.wasLate = wasLate;
    return this;
  }

   /**
   * Get wasLate
   * @return wasLate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getWasLate() {
    return wasLate;
  }

  public void setWasLate(Boolean wasLate) {
    this.wasLate = wasLate;
  }

  public TimeLog loggedBy(User loggedBy) {
    this.loggedBy = loggedBy;
    return this;
  }

   /**
   * Get loggedBy
   * @return loggedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public User getLoggedBy() {
    return loggedBy;
  }

  public void setLoggedBy(User loggedBy) {
    this.loggedBy = loggedBy;
  }

  public TimeLog onMyWay(OnMyWay onMyWay) {
    this.onMyWay = onMyWay;
    return this;
  }

   /**
   * Get onMyWay
   * @return onMyWay
  **/
  @ApiModelProperty(example = "null", value = "")
  public OnMyWay getOnMyWay() {
    return onMyWay;
  }

  public void setOnMyWay(OnMyWay onMyWay) {
    this.onMyWay = onMyWay;
  }

  public TimeLog actions(List<ActionsEnum> actions) {
    this.actions = actions;
    return this;
  }

  public TimeLog addActionsItem(ActionsEnum actionsItem) {
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ActionsEnum> getActions() {
    return actions;
  }

  public void setActions(List<ActionsEnum> actions) {
    this.actions = actions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeLog timeLog = (TimeLog) o;
    return Objects.equals(this.workOrderId, timeLog.workOrderId) &&
        Objects.equals(this.timeZone, timeLog.timeZone) &&
        Objects.equals(this.in, timeLog.in) &&
        Objects.equals(this.out, timeLog.out) &&
        Objects.equals(this.devices, timeLog.devices) &&
        Objects.equals(this.hours, timeLog.hours) &&
        Objects.equals(this.verified, timeLog.verified) &&
        Objects.equals(this.wasLate, timeLog.wasLate) &&
        Objects.equals(this.loggedBy, timeLog.loggedBy) &&
        Objects.equals(this.onMyWay, timeLog.onMyWay) &&
        Objects.equals(this.actions, timeLog.actions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workOrderId, timeZone, in, out, devices, hours, verified, wasLate, loggedBy, onMyWay, actions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeLog {\n");
    
    sb.append("    workOrderId: ").append(toIndentedString(workOrderId)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    in: ").append(toIndentedString(in)).append("\n");
    sb.append("    out: ").append(toIndentedString(out)).append("\n");
    sb.append("    devices: ").append(toIndentedString(devices)).append("\n");
    sb.append("    hours: ").append(toIndentedString(hours)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("    wasLate: ").append(toIndentedString(wasLate)).append("\n");
    sb.append("    loggedBy: ").append(toIndentedString(loggedBy)).append("\n");
    sb.append("    onMyWay: ").append(toIndentedString(onMyWay)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

