/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.EventUpdateScheduleByWorkOrder;

/**
 * UpdateModelParams
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class UpdateModelParams {
  @Json(name="model")
  private Object model = null;

  @Json(name="updateScheduleByWorkOrder")
  private EventUpdateScheduleByWorkOrder updateScheduleByWorkOrder = null;

  public UpdateModelParams model(Object model) {
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @ApiModelProperty(example = "null", value = "")
  public Object getModel() {
    return model;
  }

  public void setModel(Object model) {
    this.model = model;
  }

  public UpdateModelParams updateScheduleByWorkOrder(EventUpdateScheduleByWorkOrder updateScheduleByWorkOrder) {
    this.updateScheduleByWorkOrder = updateScheduleByWorkOrder;
    return this;
  }

   /**
   * Get updateScheduleByWorkOrder
   * @return updateScheduleByWorkOrder
  **/
  @ApiModelProperty(example = "null", value = "")
  public EventUpdateScheduleByWorkOrder getUpdateScheduleByWorkOrder() {
    return updateScheduleByWorkOrder;
  }

  public void setUpdateScheduleByWorkOrder(EventUpdateScheduleByWorkOrder updateScheduleByWorkOrder) {
    this.updateScheduleByWorkOrder = updateScheduleByWorkOrder;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateModelParams updateModelParams = (UpdateModelParams) o;
    return Objects.equals(this.model, updateModelParams.model) &&
        Objects.equals(this.updateScheduleByWorkOrder, updateModelParams.updateScheduleByWorkOrder);
  }

  @Override
  public int hashCode() {
    return Objects.hash(model, updateScheduleByWorkOrder);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateModelParams {\n");
    
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    updateScheduleByWorkOrder: ").append(toIndentedString(updateScheduleByWorkOrder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

