/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UpdateModelMetadataData;
import io.swagger.client.model.UpdateModelMetadataUniversalContext;

/**
 * UpdateModelMetadata
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class UpdateModelMetadata {
  @Json(name="universal_context")
  private UpdateModelMetadataUniversalContext universalContext = null;

  @Json(name="data")
  private UpdateModelMetadataData data = null;

  public UpdateModelMetadata universalContext(UpdateModelMetadataUniversalContext universalContext) {
    this.universalContext = universalContext;
    return this;
  }

   /**
   * Get universalContext
   * @return universalContext
  **/
  @ApiModelProperty(example = "null", value = "")
  public UpdateModelMetadataUniversalContext getUniversalContext() {
    return universalContext;
  }

  public void setUniversalContext(UpdateModelMetadataUniversalContext universalContext) {
    this.universalContext = universalContext;
  }

  public UpdateModelMetadata data(UpdateModelMetadataData data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(example = "null", value = "")
  public UpdateModelMetadataData getData() {
    return data;
  }

  public void setData(UpdateModelMetadataData data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateModelMetadata updateModelMetadata = (UpdateModelMetadata) o;
    return Objects.equals(this.universalContext, updateModelMetadata.universalContext) &&
        Objects.equals(this.data, updateModelMetadata.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(universalContext, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateModelMetadata {\n");
    
    sb.append("    universalContext: ").append(toIndentedString(universalContext)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

