/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Company;
import java.util.ArrayList;
import java.util.List;

/**
 * UserCompany
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class UserCompany {
  @Json(name="id")
  private Integer id = null;

  @Json(name="name")
  private String name = null;

  @Json(name="features")
  private List<String> features = new ArrayList<String>();

  @Json(name="technicians")
  private Integer technicians = null;

  @Json(name="vendors")
  private List<Company> vendors = new ArrayList<Company>();

  public UserCompany id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public UserCompany name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UserCompany features(List<String> features) {
    this.features = features;
    return this;
  }

  public UserCompany addFeaturesItem(String featuresItem) {
    this.features.add(featuresItem);
    return this;
  }

   /**
   * Get features
   * @return features
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getFeatures() {
    return features;
  }

  public void setFeatures(List<String> features) {
    this.features = features;
  }

  public UserCompany technicians(Integer technicians) {
    this.technicians = technicians;
    return this;
  }

   /**
   * Get technicians
   * @return technicians
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTechnicians() {
    return technicians;
  }

  public void setTechnicians(Integer technicians) {
    this.technicians = technicians;
  }

  public UserCompany vendors(List<Company> vendors) {
    this.vendors = vendors;
    return this;
  }

  public UserCompany addVendorsItem(Company vendorsItem) {
    this.vendors.add(vendorsItem);
    return this;
  }

   /**
   * Get vendors
   * @return vendors
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Company> getVendors() {
    return vendors;
  }

  public void setVendors(List<Company> vendors) {
    this.vendors = vendors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserCompany userCompany = (UserCompany) o;
    return Objects.equals(this.id, userCompany.id) &&
        Objects.equals(this.name, userCompany.name) &&
        Objects.equals(this.features, userCompany.features) &&
        Objects.equals(this.technicians, userCompany.technicians) &&
        Objects.equals(this.vendors, userCompany.vendors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, features, technicians, vendors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserCompany {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    technicians: ").append(toIndentedString(technicians)).append("\n");
    sb.append("    vendors: ").append(toIndentedString(vendors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

