/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UserBy;

/**
 * UserBlocked
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class UserBlocked {
  @Json(name="at")
  private String at = null;

  @Json(name="by")
  private UserBy by = null;

  public UserBlocked at(String at) {
    this.at = at;
    return this;
  }

   /**
   * Get at
   * @return at
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAt() {
    return at;
  }

  public void setAt(String at) {
    this.at = at;
  }

  public UserBlocked by(UserBy by) {
    this.by = by;
    return this;
  }

   /**
   * Get by
   * @return by
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserBy getBy() {
    return by;
  }

  public void setBy(UserBy by) {
    this.by = by;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserBlocked userBlocked = (UserBlocked) o;
    return Objects.equals(this.at, userBlocked.at) &&
        Objects.equals(this.by, userBlocked.by);
  }

  @Override
  public int hashCode() {
    return Objects.hash(at, by);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserBlocked {\n");
    
    sb.append("    at: ").append(toIndentedString(at)).append("\n");
    sb.append("    by: ").append(toIndentedString(by)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

