/*
 * RESTful API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fieldnation.data.bv2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Assignee;
import io.swagger.client.model.AttachmentFolders;
import io.swagger.client.model.Bundle;
import io.swagger.client.model.Company;
import io.swagger.client.model.Contacts;
import io.swagger.client.model.CustomFields;
import io.swagger.client.model.Holds;
import io.swagger.client.model.Location;
import io.swagger.client.model.Manager;
import io.swagger.client.model.Messages;
import io.swagger.client.model.Milestones;
import io.swagger.client.model.Pays;
import io.swagger.client.model.Project;
import io.swagger.client.model.RichText;
import io.swagger.client.model.Schedule;
import io.swagger.client.model.SelectionRule;
import io.swagger.client.model.Shipments;
import io.swagger.client.model.Status;
import io.swagger.client.model.Tasks;
import io.swagger.client.model.TypeOfWork;
import java.util.ArrayList;
import java.util.List;

/**
 * WorkOrder
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-20T21:04:59.764Z")
public class WorkOrder {
  @Json(name="work_order_id")
  private Integer workOrderId = null;

  @Json(name="networks")
  private List<String> networks = new ArrayList<String>();

  @Json(name="correlation_id")
  private String correlationId = null;

  @Json(name="title")
  private String title = null;

  @Json(name="assignee")
  private Assignee assignee = null;

  @Json(name="type_of_work")
  private TypeOfWork typeOfWork = null;

  @Json(name="manager")
  private Manager manager = null;

  @Json(name="bundle")
  private Bundle bundle = null;

  @Json(name="project")
  private Project project = null;

  @Json(name="client")
  private Company client = null;

  @Json(name="company")
  private Company company = null;

  @Json(name="custom_fields")
  private CustomFields customFields = null;

  @Json(name="w2")
  private Boolean w2 = null;

  @Json(name="role")
  private String role = null;

  @Json(name="location")
  private Location location = null;

  @Json(name="schedule")
  private Schedule schedule = null;

  @Json(name="pay")
  private Pays pay = null;

  @Json(name="contacts")
  private Contacts contacts = null;

  @Json(name="shipments")
  private Shipments shipments = null;

  @Json(name="attachments")
  private AttachmentFolders attachments = null;

  @Json(name="tasks")
  private Tasks tasks = null;

  @Json(name="messages")
  private Messages messages = null;

  @Json(name="status")
  private Status status = null;

  @Json(name="holds")
  private Holds holds = null;

  @Json(name="milestones")
  private Milestones milestones = null;

  @Json(name="description")
  private RichText description = null;

  @Json(name="confidential")
  private RichText confidential = null;

  @Json(name="policy_and_procedures")
  private RichText policyAndProcedures = null;

  @Json(name="standard_instructions")
  private RichText standardInstructions = null;

  @Json(name="selection_rule")
  private SelectionRule selectionRule = null;

  public WorkOrder workOrderId(Integer workOrderId) {
    this.workOrderId = workOrderId;
    return this;
  }

   /**
   * Get workOrderId
   * @return workOrderId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWorkOrderId() {
    return workOrderId;
  }

  public void setWorkOrderId(Integer workOrderId) {
    this.workOrderId = workOrderId;
  }

  public WorkOrder networks(List<String> networks) {
    this.networks = networks;
    return this;
  }

  public WorkOrder addNetworksItem(String networksItem) {
    this.networks.add(networksItem);
    return this;
  }

   /**
   * Get networks
   * @return networks
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getNetworks() {
    return networks;
  }

  public void setNetworks(List<String> networks) {
    this.networks = networks;
  }

  public WorkOrder correlationId(String correlationId) {
    this.correlationId = correlationId;
    return this;
  }

   /**
   * Get correlationId
   * @return correlationId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCorrelationId() {
    return correlationId;
  }

  public void setCorrelationId(String correlationId) {
    this.correlationId = correlationId;
  }

  public WorkOrder title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public WorkOrder assignee(Assignee assignee) {
    this.assignee = assignee;
    return this;
  }

   /**
   * Get assignee
   * @return assignee
  **/
  @ApiModelProperty(example = "null", value = "")
  public Assignee getAssignee() {
    return assignee;
  }

  public void setAssignee(Assignee assignee) {
    this.assignee = assignee;
  }

  public WorkOrder typeOfWork(TypeOfWork typeOfWork) {
    this.typeOfWork = typeOfWork;
    return this;
  }

   /**
   * Get typeOfWork
   * @return typeOfWork
  **/
  @ApiModelProperty(example = "null", value = "")
  public TypeOfWork getTypeOfWork() {
    return typeOfWork;
  }

  public void setTypeOfWork(TypeOfWork typeOfWork) {
    this.typeOfWork = typeOfWork;
  }

  public WorkOrder manager(Manager manager) {
    this.manager = manager;
    return this;
  }

   /**
   * Get manager
   * @return manager
  **/
  @ApiModelProperty(example = "null", value = "")
  public Manager getManager() {
    return manager;
  }

  public void setManager(Manager manager) {
    this.manager = manager;
  }

  public WorkOrder bundle(Bundle bundle) {
    this.bundle = bundle;
    return this;
  }

   /**
   * Get bundle
   * @return bundle
  **/
  @ApiModelProperty(example = "null", value = "")
  public Bundle getBundle() {
    return bundle;
  }

  public void setBundle(Bundle bundle) {
    this.bundle = bundle;
  }

  public WorkOrder project(Project project) {
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @ApiModelProperty(example = "null", value = "")
  public Project getProject() {
    return project;
  }

  public void setProject(Project project) {
    this.project = project;
  }

  public WorkOrder client(Company client) {
    this.client = client;
    return this;
  }

   /**
   * Get client
   * @return client
  **/
  @ApiModelProperty(example = "null", value = "")
  public Company getClient() {
    return client;
  }

  public void setClient(Company client) {
    this.client = client;
  }

  public WorkOrder company(Company company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @ApiModelProperty(example = "null", value = "")
  public Company getCompany() {
    return company;
  }

  public void setCompany(Company company) {
    this.company = company;
  }

  public WorkOrder customFields(CustomFields customFields) {
    this.customFields = customFields;
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @ApiModelProperty(example = "null", value = "")
  public CustomFields getCustomFields() {
    return customFields;
  }

  public void setCustomFields(CustomFields customFields) {
    this.customFields = customFields;
  }

  public WorkOrder w2(Boolean w2) {
    this.w2 = w2;
    return this;
  }

   /**
   * Get w2
   * @return w2
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getW2() {
    return w2;
  }

  public void setW2(Boolean w2) {
    this.w2 = w2;
  }

  public WorkOrder role(String role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public WorkOrder location(Location location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(example = "null", value = "")
  public Location getLocation() {
    return location;
  }

  public void setLocation(Location location) {
    this.location = location;
  }

  public WorkOrder schedule(Schedule schedule) {
    this.schedule = schedule;
    return this;
  }

   /**
   * Get schedule
   * @return schedule
  **/
  @ApiModelProperty(example = "null", value = "")
  public Schedule getSchedule() {
    return schedule;
  }

  public void setSchedule(Schedule schedule) {
    this.schedule = schedule;
  }

  public WorkOrder pay(Pays pay) {
    this.pay = pay;
    return this;
  }

   /**
   * Get pay
   * @return pay
  **/
  @ApiModelProperty(example = "null", value = "")
  public Pays getPay() {
    return pay;
  }

  public void setPay(Pays pay) {
    this.pay = pay;
  }

  public WorkOrder contacts(Contacts contacts) {
    this.contacts = contacts;
    return this;
  }

   /**
   * Get contacts
   * @return contacts
  **/
  @ApiModelProperty(example = "null", value = "")
  public Contacts getContacts() {
    return contacts;
  }

  public void setContacts(Contacts contacts) {
    this.contacts = contacts;
  }

  public WorkOrder shipments(Shipments shipments) {
    this.shipments = shipments;
    return this;
  }

   /**
   * Get shipments
   * @return shipments
  **/
  @ApiModelProperty(example = "null", value = "")
  public Shipments getShipments() {
    return shipments;
  }

  public void setShipments(Shipments shipments) {
    this.shipments = shipments;
  }

  public WorkOrder attachments(AttachmentFolders attachments) {
    this.attachments = attachments;
    return this;
  }

   /**
   * Get attachments
   * @return attachments
  **/
  @ApiModelProperty(example = "null", value = "")
  public AttachmentFolders getAttachments() {
    return attachments;
  }

  public void setAttachments(AttachmentFolders attachments) {
    this.attachments = attachments;
  }

  public WorkOrder tasks(Tasks tasks) {
    this.tasks = tasks;
    return this;
  }

   /**
   * Get tasks
   * @return tasks
  **/
  @ApiModelProperty(example = "null", value = "")
  public Tasks getTasks() {
    return tasks;
  }

  public void setTasks(Tasks tasks) {
    this.tasks = tasks;
  }

  public WorkOrder messages(Messages messages) {
    this.messages = messages;
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @ApiModelProperty(example = "null", value = "")
  public Messages getMessages() {
    return messages;
  }

  public void setMessages(Messages messages) {
    this.messages = messages;
  }

  public WorkOrder status(Status status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public Status getStatus() {
    return status;
  }

  public void setStatus(Status status) {
    this.status = status;
  }

  public WorkOrder holds(Holds holds) {
    this.holds = holds;
    return this;
  }

   /**
   * Get holds
   * @return holds
  **/
  @ApiModelProperty(example = "null", value = "")
  public Holds getHolds() {
    return holds;
  }

  public void setHolds(Holds holds) {
    this.holds = holds;
  }

  public WorkOrder milestones(Milestones milestones) {
    this.milestones = milestones;
    return this;
  }

   /**
   * Get milestones
   * @return milestones
  **/
  @ApiModelProperty(example = "null", value = "")
  public Milestones getMilestones() {
    return milestones;
  }

  public void setMilestones(Milestones milestones) {
    this.milestones = milestones;
  }

  public WorkOrder description(RichText description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public RichText getDescription() {
    return description;
  }

  public void setDescription(RichText description) {
    this.description = description;
  }

  public WorkOrder confidential(RichText confidential) {
    this.confidential = confidential;
    return this;
  }

   /**
   * Get confidential
   * @return confidential
  **/
  @ApiModelProperty(example = "null", value = "")
  public RichText getConfidential() {
    return confidential;
  }

  public void setConfidential(RichText confidential) {
    this.confidential = confidential;
  }

  public WorkOrder policyAndProcedures(RichText policyAndProcedures) {
    this.policyAndProcedures = policyAndProcedures;
    return this;
  }

   /**
   * Get policyAndProcedures
   * @return policyAndProcedures
  **/
  @ApiModelProperty(example = "null", value = "")
  public RichText getPolicyAndProcedures() {
    return policyAndProcedures;
  }

  public void setPolicyAndProcedures(RichText policyAndProcedures) {
    this.policyAndProcedures = policyAndProcedures;
  }

  public WorkOrder standardInstructions(RichText standardInstructions) {
    this.standardInstructions = standardInstructions;
    return this;
  }

   /**
   * Get standardInstructions
   * @return standardInstructions
  **/
  @ApiModelProperty(example = "null", value = "")
  public RichText getStandardInstructions() {
    return standardInstructions;
  }

  public void setStandardInstructions(RichText standardInstructions) {
    this.standardInstructions = standardInstructions;
  }

  public WorkOrder selectionRule(SelectionRule selectionRule) {
    this.selectionRule = selectionRule;
    return this;
  }

   /**
   * Get selectionRule
   * @return selectionRule
  **/
  @ApiModelProperty(example = "null", value = "")
  public SelectionRule getSelectionRule() {
    return selectionRule;
  }

  public void setSelectionRule(SelectionRule selectionRule) {
    this.selectionRule = selectionRule;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkOrder workOrder = (WorkOrder) o;
    return Objects.equals(this.workOrderId, workOrder.workOrderId) &&
        Objects.equals(this.networks, workOrder.networks) &&
        Objects.equals(this.correlationId, workOrder.correlationId) &&
        Objects.equals(this.title, workOrder.title) &&
        Objects.equals(this.assignee, workOrder.assignee) &&
        Objects.equals(this.typeOfWork, workOrder.typeOfWork) &&
        Objects.equals(this.manager, workOrder.manager) &&
        Objects.equals(this.bundle, workOrder.bundle) &&
        Objects.equals(this.project, workOrder.project) &&
        Objects.equals(this.client, workOrder.client) &&
        Objects.equals(this.company, workOrder.company) &&
        Objects.equals(this.customFields, workOrder.customFields) &&
        Objects.equals(this.w2, workOrder.w2) &&
        Objects.equals(this.role, workOrder.role) &&
        Objects.equals(this.location, workOrder.location) &&
        Objects.equals(this.schedule, workOrder.schedule) &&
        Objects.equals(this.pay, workOrder.pay) &&
        Objects.equals(this.contacts, workOrder.contacts) &&
        Objects.equals(this.shipments, workOrder.shipments) &&
        Objects.equals(this.attachments, workOrder.attachments) &&
        Objects.equals(this.tasks, workOrder.tasks) &&
        Objects.equals(this.messages, workOrder.messages) &&
        Objects.equals(this.status, workOrder.status) &&
        Objects.equals(this.holds, workOrder.holds) &&
        Objects.equals(this.milestones, workOrder.milestones) &&
        Objects.equals(this.description, workOrder.description) &&
        Objects.equals(this.confidential, workOrder.confidential) &&
        Objects.equals(this.policyAndProcedures, workOrder.policyAndProcedures) &&
        Objects.equals(this.standardInstructions, workOrder.standardInstructions) &&
        Objects.equals(this.selectionRule, workOrder.selectionRule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workOrderId, networks, correlationId, title, assignee, typeOfWork, manager, bundle, project, client, company, customFields, w2, role, location, schedule, pay, contacts, shipments, attachments, tasks, messages, status, holds, milestones, description, confidential, policyAndProcedures, standardInstructions, selectionRule);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkOrder {\n");
    
    sb.append("    workOrderId: ").append(toIndentedString(workOrderId)).append("\n");
    sb.append("    networks: ").append(toIndentedString(networks)).append("\n");
    sb.append("    correlationId: ").append(toIndentedString(correlationId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    typeOfWork: ").append(toIndentedString(typeOfWork)).append("\n");
    sb.append("    manager: ").append(toIndentedString(manager)).append("\n");
    sb.append("    bundle: ").append(toIndentedString(bundle)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    client: ").append(toIndentedString(client)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    w2: ").append(toIndentedString(w2)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("    pay: ").append(toIndentedString(pay)).append("\n");
    sb.append("    contacts: ").append(toIndentedString(contacts)).append("\n");
    sb.append("    shipments: ").append(toIndentedString(shipments)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    tasks: ").append(toIndentedString(tasks)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    holds: ").append(toIndentedString(holds)).append("\n");
    sb.append("    milestones: ").append(toIndentedString(milestones)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    confidential: ").append(toIndentedString(confidential)).append("\n");
    sb.append("    policyAndProcedures: ").append(toIndentedString(policyAndProcedures)).append("\n");
    sb.append("    standardInstructions: ").append(toIndentedString(standardInstructions)).append("\n");
    sb.append("    selectionRule: ").append(toIndentedString(selectionRule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

