package com.fieldnation.rpc.common;

public interface WebServiceConstants {
    String ACTION_NAME = "web_request";
    String METHOD_HTTP_WRITE = "httpwrite";
    String METHOD_HTTP_READ = "httpread";
    String METHOD_HTTP_POST_FILE = "httppostfile";

    String KEY_PARAM_DATA = "PARAM_DATA";
    String KEY_RESPONSE_CACHED = "RESPONSE_CACHED";
    String KEY_RESPONSE_CODE = "RESPONSE_CODE";
    String KEY_RESPONSE_DATA = "RESPONSE_DATA";
    String KEY_ALLOW_CACHE = "ALLOW_CACHE";
    String KEY_PARAM_CONTENT_TYPE = "PARAM_CONTENT_TYPE";
    String KEY_PARAM_OPTIONS = "PARAM_OPTIONS";
    String KEY_PARAM_PATH = "PARAM_PATH";
    String KEY_PARAM_METHOD = "PARAM_METHOD";
    String KEY_RESULT_CODE = "RESULT_CODE";
    String KEY_RESPONSE_ERROR = "RESPONSE_ERROR";
    String KEY_RESPONSE_ERROR_TYPE = "RESPONSE_ERROR_TYPE";
    String KEY_PARAM_CALLBACK = "PARAM_CALLBACK";
    String KEY_PARAM_USERNAME = "PARAM_USERNAME";
    String KEY_METHOD = "METHOD";
    String KEY_PARAM_AUTH_TOKEN = "PARAM_AUTH_TOKEN";

    String ERROR_SESSION_INVALID = "SESSION_INVALID";
    String ERROR_USER_NOT_FOUND = "USER_NOT_FOUND";
    String ERROR_NO_USERNAME = "NO_USERNAME";

    String ERROR_NONE = "NONE";
    String ERROR_NETWORK_ERROR = "NETWORK_ERROR";
    String ERROR_UNKNOWN = "UNKNOWN";
    String ERROR_HTTP_ERROR = "HTTP_ERROR";

    String KEY_PARAM_FILE_URI = "PARAM_FILE_URI";
    // String KEY_PARAM_FILE_DATA = "PARAM_FILE_DATA";
    String KEY_PARAM_FILE_DATA_INTENT = "KEY_PARAM_FILE_DATA_INTENT";
    String KEY_PARAM_FILE_FIELD_NAME = "PARAM_FILE_FIELD_NAME";
    String KEY_PARAM_FILE_NAME = "PARAM_FILE_NAME";
    String KEY_PARAM_FIELD_MAP = "PARAM_FIELD_MAP";
    String KEY_PARAM_NOTIFICATION_INTENT = "PARAM_NOTIFICATION_INTENT";
}
