package com.fieldnation.rpc.common;

interface WebServiceConstants {
    String KEY_PARAM_REQUEST = "KEY_PARAM_REQUEST";
    String KEY_PARAM_RESULT_CODE = "RESULT_CODE";
    String KEY_PARAM_CALLBACK = "PARAM_CALLBACK";
    String KEY_PARAM_ALLOW_CACHE = "ALLOW_CACHE";

//     String KEY_PARAM_DATA = "PARAM_DATA";
//     String KEY_PARAM_CONTENT_TYPE = "PARAM_CONTENT_TYPE";
//     String KEY_PARAM_OPTIONS = "PARAM_OPTIONS";
//     String KEY_PARAM_PATH = "PARAM_PATH";
//     String KEY_PARAM_METHOD = "PARAM_METHOD";
//     String KEY_METHOD = "METHOD";

    String KEY_RESPONSE_ERROR = "RESPONSE_ERROR";
    String KEY_RESPONSE_ERROR_TYPE = "RESPONSE_ERROR_TYPE";
    String KEY_RESPONSE_CACHED = "RESPONSE_CACHED";
    String KEY_RESPONSE_CODE = "RESPONSE_CODE";
    String KEY_RESPONSE_DATA = "RESPONSE_DATA";

    String ERROR_NONE = "NONE";
    String ERROR_NETWORK_ERROR = "NETWORK_ERROR";
    String ERROR_UNKNOWN = "UNKNOWN";
    String ERROR_HTTP_ERROR = "HTTP_ERROR";
    String ERROR_SESSION_INVALID = "SESSION_INVALID";

    String KEY_PARAM_FILE_URI = "PARAM_FILE_URI";
    // String KEY_PARAM_FILE_DATA = "PARAM_FILE_DATA";
//     String KEY_PARAM_FILE_DATA_INTENT = "KEY_PARAM_FILE_DATA_INTENT";
//     String KEY_PARAM_FILE_FIELD_NAME = "PARAM_FILE_FIELD_NAME";
//     String KEY_PARAM_FILE_NAME = "PARAM_FILE_NAME";
//     String KEY_PARAM_FIELD_MAP = "PARAM_FIELD_MAP";
//     String KEY_PARAM_NOTIFICATION_INTENT = "PARAM_NOTIFICATION_INTENT";
}
