package com.fieldnation.topics;

/**
 * Created by michael.carver on 12/12/2014.
 */
interface TopicConstants {
    String ACTION = "ACTION";
    String ACTION_REGISTER_LISTENER = "ACTION_REGISTER_LISTENER";
    String ACTION_UNREGISTER_LISTENER = "ACTION_UNREGISTER_LISTENER";
    String ACTION_DISPATCH_EVENT = "ACTION_DISPATCH_EVENT";
    String ACTION_DELETE_CLIENT = "ACTION_DELETE_CLIENT";

    String PARAM_TOPIC_ID = "PARAM_TOPIC_ID";
    String PARAM_TOPIC_RECEIVER = "PARAM_TOPIC_RECEIVER";
    String PARAM_TOPIC_PARCEL = "PARAM_TOPIC_PARCEL";
    String PARAM_TAG = "PARAM_TAG";
    String PARAM_KEEP_LAST_SENT = "PARAM_KEEP_LAST_SENT";

    String PARAM_RESULT_CODE = "PARAM_RESULT_CODE";
}
